### ISSUE TITLE
用deepfm为什么每次跑出来的结果都不一样，有什么方法可以使他们一样？

### ISSUE THREAD

**Issue by huminwudi** [shenweichen/DeepCTR#101]
**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
这个属于正常现象，尤其是数据不够充分的情况下，主要原因是由于Tensorflow底层的多线程运行机制以及一些具有随机性的op和random seed导致的。如果想让每次运行的结果尽量一致，可以考虑使用CPU运行程序，并且指定单线程运行，同时固定random seed，包括python自身的，Numpy的还有tensorflow的

**Comment by huminwudi** [comment]
好的 谢谢！

**Comment by sneffort** [comment]
> 好的 谢谢！

你试成功了么，看起来做了哪些单线程和固定seed的操作后，貌似也还是会各种随机？

**Comment by sneffort** [comment]
> 好的 谢谢！

你试成功了么，看起来做了哪些单线程和固定seed的操作后，貌似也还是会各种随机？
