### ISSUE TITLE
关于FiBiNet bilinear_type为Field-Interaction Type时输出向量尺寸不同的问题

### ISSUE THREAD

**Issue by ae2leowen** [shenweichen/DeepCTR#103]
**Describe the question(问题描述)**
你好，请教下在FiBiNet网络中，当bilinear_type为Field-Interaction Type时,(如果我没有理解错误的话)输出向量尺寸应该是N * F(F-1)/2 * T<其中N为batch_size,F为field size, T为embedding size>，这样两边concat后应该就是N * F(F-1) * T，原论文只有提到concat后是N *2F * T，是论文没有详写还是我理解错了，有空帮忙理解下，谢谢

**Additional context**
另外，我看到作者在layers/interaction.py/class BilinearInteraction(Layer)/compute_output_shape中有写到输出是N * F(F-1)/2 * T，但看起来好像是对于三种bilinear_type都是这个大小？

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.5.1,]

**Comment by shenweichen** [comment]
1. concat 后应该是 N * F(F-1) * T
2. 三种type的输出shape都是一样的
