### ISSUE TITLE
cannot save then load model

### ISSUE THREAD

**Issue by ulrych8** [shenweichen/DeepCTR#104]
I tried to save the CCPM model and load it in a different file.

I followed the instructions here [https://deepctr-doc.readthedocs.io/en/latest/FAQ.html](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html)
![image](https://user-images.githubusercontent.com/32176478/61281844-9eb61700-a7ba-11e9-8d0f-92c5eb980fe0.png)

However this raise an ImportError : `ImportError: cannot import name 'custom_objects'`
(even with `from deepctr.layers.utils import custom_objects`)

Hope you'll understand what I do wrong,
Thank you for your help

**Comment by ulrych8** [comment]
I'm sorry my mistake I was runing python file from my terminal with python 2 instead of python3

**Comment by ulrych8** [comment]
I tried an other way found in [https://jovianlin.io/saving-loading-keras-models/](https://jovianlin.io/saving-loading-keras-models/)

And this method raise `ValueError: Unknown layer: Hash`

**Comment by ulrych8** [comment]
The page isn't update you should use : `from deepctr.layers import custom_objects`

**Comment by shenweichen** [comment]
@ulrych8 thanks , i will fix the docs in the  next release.
