### ISSUE TITLE
SingleFeat and VarLenFeat removed?

### ISSUE THREAD

**Issue by CarlosVaquero** [shenweichen/DeepCTR#105]
Since the last commit, both SingleFeat or VarLenFeat classes have been removed from utils.py.  Would you suggest an alternative to this?

**Comment by shenweichen** [comment]
hi,`SingleFeat`and`VarLenFeat` are changed to `SparseFeat`,`DenseFeat` and `VarlenSparseFeat`,please refer to the website of the usage https://deepctr-doc.readthedocs.io/en/latest/Examples.html
