### ISSUE TITLE
Use of linear_feature_columns and dnn_feature_columns

### ISSUE THREAD

**Issue by ulrych8** [shenweichen/DeepCTR#111]
Hello, 
It's not quite clear to me how to use dense_feature_list  and sparse_feature_list in linear or dnn feature columns.
Before the update version you could have
` linear_feature_columns = dnn_feature_columns = dense_feature_list + sparse_feature_list  `
for most of the model and it worked; but it does not seem to work anymore.

So my question is :   **How can I use dense_feature_list in both linear_feature_columns and dnn_feature_columns ?**

**Comment by shenweichen** [comment]
@ulrych8 hi,sorry for the inconvenience caused by the recent frequent changes if the API.
Now in v0.5.2 you can use dense features and sparse features like following:
```python
linear_feature_colums = [SparseFeat(feat, data[feat].nunique())
                           for feat in sparse_features] + [DenseFeat(feat, 1,)
                          for feat in dense_features]
```
you can also read the examples in docs for detail 
https://deepctr-doc.readthedocs.io/en/latest/Examples.html#classification-criteo

**Comment by ulrych8** [comment]
Thank you !
