### ISSUE TITLE
DIN模型样例代码run_din.py运行错误

### ISSUE THREAD

**Issue by waterbeach** [shenweichen/DeepCTR#112]
运行 https://github.com/shenweichen/DeepCTR/blob/master/examples/run_din.py报错 ：
..../site-packages/deepctr/layers/sequence.py:198 call *
 outputs._uses_learning_phase = attention_score._uses_learning_phase
 AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
请问如何解决呢？
**Operating environment(运行环境):**
 - python version 3.6
 - tensorflow version 1.4.0 
 - deepctr version 0.5.2

**Comment by Lunargithub** [comment]
遇到了一样的问题，自己在尝试修改DIN模型的时候运行也会出现这个错误，请问需要修改什么吗T_T

**Comment by shenweichen** [comment]
运行程序的tensorflow 和deepctr版本是什么？

**Comment by waterbeach** [comment]
> 运行程序的tensorflow 和deepctr版本是什么？

tensorflow version 1.14.0
deepctr version 0.5.2

改成tensorflow 1.12也报错

**Comment by shenweichen** [comment]
`run_din.py`里面第10行的`DenseFeat('score', 0)`改成`DenseFeat('score', 1)`就可以了

**Comment by eckolemon** [comment]
> `run_din.py`里面第10行的`DenseFeat('score', 0)`改成`DenseFeat('score', 1)`就可以了

改了以后依旧会有这个错误

**Comment by eckolemon** [comment]
> 运行 [https://github.com/shenweichen/DeepCTR/blob/master/examples/run_din.py报错](https://github.com/shenweichen/DeepCTR/blob/master/examples/run_din.py%E6%8A%A5%E9%94%99) ：
> ..../site-packages/deepctr/layers/sequence.py:198 call *
> outputs._uses_learning_phase = attention_score._uses_learning_phase
> AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
> 请问如何解决呢？
> **Operating environment(运行环境):**
> 
> * python version 3.6
> * tensorflow version 1.4.0
> * deepctr version 0.5.2

请问你解决这个问题了吗？我也遇到了

**Comment by shenweichen** [comment]
@Espylapiza 你这个是tf版本有问题，先用1.4试试

**Comment by eckolemon** [comment]
> @Espylapiza 你这个是tf版本有问题，先用1.4试试

这版本也太低了吧，我们不可能一直只用1.4版本的tensorflow吧，作者可以优化一下代码吗

**Comment by shenweichen** [comment]
@eckolemon 1.12也可以。

**Comment by eckolemon** [comment]
> @eckolemon 1.12也可以。

1.14就不行。请问具体是哪个地方的问题呢？

**Comment by shenweichen** [comment]
@eckolemon 这个目前一两句解释不清，你们是公司用吗，公司一般还是1.4用的多吧

**Comment by waterbeach** [comment]
> > 运行 [https://github.com/shenweichen/DeepCTR/blob/master/examples/run_din.py报错](https://github.com/shenweichen/DeepCTR/blob/master/examples/run_din.py%E6%8A%A5%E9%94%99) ：
> > ..../site-packages/deepctr/layers/sequence.py:198 call *
> > outputs._uses_learning_phase = attention_score._uses_learning_phase
> > AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
> > 请问如何解决呢？
> > **Operating environment(运行环境):**
> > 
> > * python version 3.6
> > * tensorflow version 1.4.0
> > * deepctr version 0.5.2
> 
> 请问你解决这个问题了吗？我也遇到了

tf版本改成 1.12 
然后run_din.py里面第10行的DenseFeat('score', 0)改成DenseFeat('score', 1)就可以了
