### ISSUE TITLE
some questions about the dsin example

### ISSUE THREAD

**Issue by youchika** [shenweichen/DeepCTR#113]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
I'm trying to understand the example of the dsin network example and it somewhat hard for me, so I have couple of questions

1. is there any relation between users and sessions in the example?
on [issue#86](https://github.com/shenweichen/DeepCTR/issues/86)
you said that the third user doesn't have any historical behaviour, so does that mean that sess1 is relate to uid=0 and sess2 relate to uid=1 and uid=2 is the one without any historical behaviour?

2. are the sparse features are the data itself or encoded version of it?
I'm trying to see the reassemble to criteo or the movielens in the docs example to understand it.
so if we take for example the users id, is uid a column in the dataset like C columns in criteo? so it could be for example [1,2,3,2,4,2,2,5] if we had more data or is it just a list that indicate the unique IDs of users in the dataset?
like how would the raw data of this example would look like?
cause it feels that for this example the data was already "preprocessed" and everything so hard to understand how features are look like and where is the separation between different training samples.

3. what is item gender in a session? 
on sess1 on the 1st session iid=1 gets igender=1 but on session 2 same iid=1 get igender=2
what is the connection between item and item gender and why item gender is a behaviour_feature
I'll generalize the question a little bit, what determine which feature is behaviour feature that goes into the bi-lstm and which one is not and just used for embeddings?

4. what are the y/target-labels means in the code, I guess it means click or not clicked so y=[clicked, not-clicked, clicked]. but y[0] which is clicked means click of what?  sess1 or sess2 or entirely something else? 

6. is there a chance to add a doc example to the docs about dsin using the movielens dataset or even criteo, movielens is little bit preferable cause the feature names there are not single letter so it will better for me and others to understand?

thank you

**Comment by shenweichen** [comment]
hi @youchika ,I am sorry for the confusion of the example, and I will refine it  in the future.

> 1. is there any relation between users and sessions in the example?
> on issue#86
> you said that the third user doesn't have any historical behaviour, so does that mean that sess1 is relate to uid=0 and sess2 relate to uid=1 and uid=2 is the one without any historical behaviour?
> 
yes,sess1 is relate to uid=0 and sess2 relate to uid=1 and uid=2 is the one without any historical 

> 2. are the sparse features are the data itself or encoded version of it?
> I'm trying to see the reassemble to criteo or the movielens in the docs example to understand it.
> so if we take for example the users id, is uid a column in the dataset like C columns in criteo? so it could be for example [1,2,3,2,4,2,2,5] if we had more data or is it just a list that indicate the unique IDs of users in the dataset?
> like how would the raw data of this example would look like?
> cause it feels that for this example the data was already "preprocessed" and everything so hard to understand how features are look like and where is the separation between different training samples.
> 
in the example the data has been encoded.The data is created by myself and it has no actual meaning.

> 3. what is item gender in a session?
> on sess1 on the 1st session iid=1 gets igender=1 but on session 2 same iid=1 get igender=2
> what is the connection between item and item gender and why item gender is a behaviour_feature
> I'll generalize the question a little bit, what determine which feature is behaviour feature that goes into the bi-lstm and which one is not and just used for embeddings?

sorry for this mistake,in fact each `iid` has its unique `igender`,`igender` is the side information of `iid` indicates that which gender will prefer this item.
usually we use itemids that user clicked,liked or buyed as user behaviour along with some side information features of the item

> 4. what are the y/target-labels means in the code, I guess it means click or not clicked so y=[clicked, not-clicked, clicked]. but y[0] which is clicked means click of what? sess1 or sess2 or entirely something else?

`y` means the label that indicates whether user clicked the item in each sample.in this example,we have 3 samples,in each sample there are 3 sessions for each user.

> 5. is there a chance to add a doc example to the docs about dsin using the movielens dataset or even criteo, movielens is little bit preferable cause the feature names there are not single letter so it will better for me and others to understand?

here is a code of paper Code for the IJCAI'19 paper "Deep Session Interest Network for Click-Through Rate Prediction"  [link](https://github.com/shenweichen/DSIN)
