### ISSUE TITLE
InvalidArgumentError错误求助

### ISSUE THREAD

**Issue by dkicenan** [shenweichen/DeepCTR#116]
代码：
def deepfm_feature(X_train, y_train, X_test, y_test=None):
    global sprase_features
    global dense_features
    fixlen_feature_columns = [SparseFeat(feat, pd.concat([X_train[feat],X_test[feat]]).nunique())
                           for feat in sprase_features] + [DenseFeat(feat, 1,)
                          for feat in dense_features]

    dnn_feature_columns = fixlen_feature_columns
    linear_feature_columns = fixlen_feature_columns

    fixlen_feature_names = get_fixlen_feature_names(linear_feature_columns + dnn_feature_columns)
    train_model_input = [X_train[name] for name in fixlen_feature_names]
    test_model_input = [X_test[name] for name in fixlen_feature_names]

    model = DeepFM(linear_feature_columns, dnn_feature_columns, task='binary')
    model.compile("adam", "binary_crossentropy",
                  metrics=['binary_crossentropy'], )

    history = model.fit(train_model_input, y_train,
                        batch_size=256, epochs=200, verbose=2, validation_split=0.2, )
    pred_ans = model.predict(test_model_input, batch_size=256)
    return pred_ans

错误描述：InvalidArgumentError: indices[16,0] = 5 is not in [0, 5)
	 [[{{node sparse_emb_id_32/embedding_lookup}}]]

之前可以运行Deepfm, 我在做一些特征工程够，就报这个错误，请问这个错误什么原因呀？

**Comment by shenweichen** [comment]
可能没有编码吧，或者试试`SparseFeat`里加上` use_hash=True`
