### ISSUE TITLE
sparse_embedding_list is empty and gives an error A `Concatenate` layer should be called on a list of at least 2 inputs

### ISSUE THREAD

**Issue by shriramhr** [shenweichen/DeepCTR#118]
hi,
I get this error after doing this step:
model_deepfm = DeepFM(linear_feature_columns=sparse_feature_list,dnn_feature_columns=dense_feature_list,use_fm=True, dnn_hidden_units=(128, 128),embedding_size=16,l2_reg_linear=0.1, l2_reg_embedding=0.1, l2_reg_dnn=0, init_std=0.0001, seed=1024, dnn_dropout=0,
           dnn_activation='sigmoid', dnn_use_bn=False, task='binary')

This is the following error: 
`ValueError                                Traceback (most recent call last)
<ipython-input-106-dccce6ce428b> in <module>
      1 model_deepfm = DeepFM(linear_feature_columns=sparse_feature_list,dnn_feature_columns=dense_feature_list,use_fm=True, dnn_hidden_units=(128, 128),embedding_size=16,l2_reg_linear=0.1, l2_reg_embedding=0.1, l2_reg_dnn=0, init_std=0.0001, seed=1024, dnn_dropout=0,
----> 2            dnn_activation='sigmoid', dnn_use_bn=False, task='binary')

/usr/local/lib/python3.5/dist-packages/deepctr/models/deepfm.py in DeepFM(linear_feature_columns, dnn_feature_columns, embedding_size, use_fm, dnn_hidden_units, l2_reg_linear, l2_reg_embedding, l2_reg_dnn, init_std, seed, dnn_dropout, dnn_activation, dnn_use_bn, task)
     51                                     seed=seed, prefix='linear')
     52 
---> 53     fm_input = concat_fun(sparse_embedding_list, axis=1)
     54     fm_logit = FM()(fm_input)
     55 

/usr/local/lib/python3.5/dist-packages/deepctr/layers/utils.py in concat_fun(inputs, axis)
    116         return inputs[0]
    117     else:
--> 118         return tf.keras.layers.Concatenate(axis=axis)(inputs)
    119 
    120 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    536       if not self.built:
    537         # Build layer if applicable (if the `build` method has been overridden).
--> 538         self._maybe_build(inputs)
    539         # We must set self.built since user defined build functions are not
    540         # constrained to set self.built.

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   1601     # Only call `build` if the user has manually overridden the build method.
   1602     if not hasattr(self.build, '_is_default'):
-> 1603       self.build(input_shapes)
   1604 
   1605   def __setattr__(self, name, value):

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/tf_utils.py in wrapper(instance, input_shape)
    149       else:
    150         input_shape = tuple(tensor_shape.TensorShape(input_shape).as_list())
--> 151     output_shape = fn(instance, input_shape)
    152     if output_shape is not None:
    153       if isinstance(output_shape, list):

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/merge.py in build(self, input_shape)
    377     # Used purely for shape validation.
    378     if not isinstance(input_shape, list) or len(input_shape) < 2:
--> 379       raise ValueError('A `Concatenate` layer should be called '
    380                        'on a list of at least 2 inputs')
    381     if all(shape is None for shape in input_shape):

ValueError: A `Concatenate` layer should be called on a list of at least 2 inputs
`

**Comment by shenweichen** [comment]
The api has been changed in new version,please read the examples [here](https://deepctr-doc.readthedocs.io/en/latest/Examples.html#classification-criteo) and modify your codes
