### ISSUE TITLE
Varlen feature model save error

### ISSUE THREAD

**Issue by khlee88** [shenweichen/DeepCTR#120]
**Describe the bug(问题描述)**
Hi, I want save model for serving.
When i use varlen feature in model, there is error, not saved input signature_def.
details check bellow reproduce.
if know the problem, please let me know. 
thank you.

**To Reproduce(复现步骤)**
1. Go to 'Example "multi-value-input-movielens-with-feature-hashing-on-the-fly"'
2. Save model after compile 'model.save(path) or tf.saved_model.save(model, path)'
3. Compare with 'using varlen feature model and only using sparse feature model'
5. See error when using varlen feature 
```
tensorflow/python/keras/saving/saved_model.py:1143 call_and_return_conditional_losses  *
        return layer_call(inputs, training=training), layer.get_losses_for(inputs)
    tensorflow/python/keras/engine/network.py:753 call
        return self._run_internal_graph(inputs, training=training, mask=mask)
    tensorflow/python/keras/saving/saved_model.py:998 wrapped_call  *
        outputs, losses = call_fn(inputs)
    tensorflow/python/keras/saving/saved_model.py:1114 __call__
        self.call_collection.add_trace(*args, **kwargs)
    tensorflow/python/keras/saving/saved_model.py:1147 call_and_return_conditional_losses  *
        return layer_call(inputs), layer.get_losses_for(inputs)
    deepctr/layers/sequence.py:64 call
        "When supports_masking=True,input must support masking")

    ValueError: When supports_masking=True,input must support masking
```
6.  See there is no inputs when you command this 'saved_model_cli show --dir $path --all'

**Operating environment(运行环境):**
 - python version [3.5, 3.7]
 - tensorflow version [2.0 beta1]
 - deepctr version [e.g. 0.6]

**Additional context**

**Comment by hecongqing** [comment]
Yeah,   I also have the same problem!
