### ISSUE TITLE
build_input_feature dimension of sparse/dense feature

### ISSUE THREAD

**Issue by littlebeandog** [shenweichen/DeepCTR#122]
I've noticed there a snap in function build_input_feature
```python3
    if include_fixlen:
        for fc in feature_columns:
            if isinstance(fc, SparseFeat):
                input_features[fc.name] = Input(
                    shape=(1,), name=prefix + fc.name, dtype=fc.dtype)
            elif isinstance(fc, DenseFeat):
                input_features[fc.name] = Input(
                    shape=(fc.dimension,), name=prefix + fc.name, dtype=fc.dtype)
```
Should shape of sparse be `(fc.dimension,)` and shape of dense be `(1,)`?

**Comment by shenweichen** [comment]
we consider  sparse feature as a single id feature like `1`or `5`,and dense feature is a dense vector like `[0.5,0.1]` or `[0.3]`.
so shape of sparse is `(1,)` and shape of dense is `fc.dimension`

**Comment by littlebeandog** [comment]
Got it, thanks
