### ISSUE TITLE
请问支持超大维度的uid和itemid么？

### ISSUE THREAD

**Issue by sneffort** [shenweichen/DeepCTR#124]
请问支持超大维度的uid和itemid么？例如user在几亿级别，item在几千万级别，似乎在加载参数的情况下就显存就oom了？

**Comment by shenweichen** [comment]
支持的，不过那个版本是在公司内部做的，暂时还没有对外公开，可能需要先自行修改一下~

**Comment by sneffort** [comment]
> 支持的，不过那个版本是在公司内部做的，暂时还没有对外公开，可能需要先自行修改一下~

能简单说下在哪方面进行修改么，多谢

**Comment by shenweichen** [comment]
也可以试试做特征哈希

**Comment by sneffort** [comment]
> 也可以试试做特征哈希

特征哈希的话，是不是相当于某些不同的特征共用一些同样的参数了

**Comment by wannibar** [comment]
> 支持的，不过那个版本是在公司内部做的，暂时还没有对外公开，可能需要先自行修改一下~

同问主要是在哪些方面进行改造～～

**Comment by guotong1988** [comment]
划重点：特征哈希
