### ISSUE TITLE
Multiclass classfication task

### ISSUE THREAD

**Issue by licesonw** [shenweichen/DeepCTR#128]
I am trying to apply the CTR models to a multiclass classfication problem.

I have seen it is party implemented in the PredictionLayer class:
`if task not in ["binary", "multiclass", "regression"]:
      raise ValueError("task must be binary,multiclass or regression")`

However, the 'multiclass' case is not considered in the call method.

**Comment by shenweichen** [comment]
Sorry that the multiclass is not currently supported, the main reason is that some models naturally do not support multiclass classification(such as FM-based models).We need to modify the model according to the specific situation.

**Comment by licesonw** [comment]
Yes that's true, in the publications they only ever use binary classification and regression.Probably because the actual use case is CTR prediction, which usually is binary.
Is there anything that keeps us from just extending the output layer to >1 neurons? What do you think?

This would make these models very interesting for other use cases.

**Comment by klimentij** [comment]
I have the same question
