### ISSUE TITLE
参考样例使用自定义的模型输入时，DIEN无法正常建模

### ISSUE THREAD

**Issue by moneyml** [shenweichen/DeepCTR#130]
使用自定义的模型输入时，总是无法正确匹配shape，这是什么问题呢？
![error](https://user-images.githubusercontent.com/28591314/64120175-1ae9d580-cdce-11e9-8adc-7ce0927c4e15.PNG)

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.5.2,]

**Comment by shenweichen** [comment]
更新下最新版本的deepctr试试 
```bash
pip install -U deepctr
```
