### ISSUE TITLE
question in DIEN example

### ISSUE THREAD

**Issue by better629** [shenweichen/DeepCTR#131]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
The DIEN example defines `VarLenSparseFeat(hist_item) ` of history sequence(item). But what if the scale of `item` is large, the `hist_item` value will be large too and cost a lot of memory.

In my solution, the unique num of item =120088, and the example num = 200217. Then the program is killed in a 128G machine. Is there a way to avoid this.

Thank you.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.5]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.6.0,]

**Comment by shenweichen** [comment]
you can try using feature hashing to reduce the scale of `item` of according to https://deepctr-doc.readthedocs.io/en/latest/Quick-Start.html#step-3-generate-feature-columns
