### ISSUE TITLE
different predictions between original and saved models

### ISSUE THREAD

**Issue by mtsang** [shenweichen/DeepCTR#133]
Hi,

I use the suggested code for saving and loading your models, shown below, but I get different predictions for the model before saving and the model after loading. I noticed this same issue when checking the test case for DeepFM. I'm wondering if this is a known issue.

Thanks

```
from tensorflow.python.keras.models import  save_model,load_model
model = DeepFM()
save_model(model, 'DeepFM.h5')# save_model, same as before

from deepctr.layers import custom_objects
model = load_model('DeepFM.h5',custom_objects)# load_model,just add a parameter
```

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.12.3]
 - deepctr version [e.g. 0.6.0]

**Comment by mtsang** [comment]
I tried the test case on a different server that has tensorflow 1.14. Not exactly sure if this reason behind the different predictions, but doesn't seem to be an issue with DeepCTR, so closing this issue

**Comment by rajeshshrestha** [comment]
In my case, NFFM with weight saving and loading is producing the same result but with FGCNN, I am getting different prediction values (with the model after training and with new model loading the saved weight)
