### ISSUE TITLE
using multidimensional dense features

### ISSUE THREAD

**Issue by eyalmazuz** [shenweichen/DeepCTR#135]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
I took the criteo example from the website and added a new dense feature column I14

using
`data['I14'] = [[1,1,]]*data.shape[0]`

after that I changed the fixlen_feature_columns into this:

`fixlen_feature_columns = [SparseFeat(feat, data[feat].nunique())
                           for feat in sparse_features] + [DenseFeat(feat, 1,)
                          for feat in dense_features] + [DenseFeat('I14', 2)]`

and tried to run the model I get the following error

> ValueError: Error when checking input: expected I14 to have shape (2, ) but got array with shape (1, )

but I checked the dataframe and every row, the array shape is (2, )
if I change Dense feature to have dimension 1 instead of 2 I get this error

>  ValueError: setting an array element with sequence.

what I'm doing wrong?
and what is the right way to add dense features that are vectors (have more than 1 numerical value) into the models?

**Operating environment(运行环境):**
 - python version [e.g. 3.6] 3.6
 - tensorflow version [e.g. 1.4.0,] 1.14
 - deepctr version [e.g. 0.5.2,] 0.6.1

**Comment by shenweichen** [comment]
please refer to the part 5 of FAQ https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-add-a-long-dense-feature-vector-as-a-input-to-the-model

**Comment by eyalmazuz** [comment]
I read part 5 of the FAQ
but I still get:

> ValueError: Error when checking input: expected I14 to have shape (2, ) but got array with shape (1, )
