### ISSUE TITLE
Multi-value Input 不支持全部都是 Nan, 即 all 0 的情况 

### ISSUE THREAD

**Issue by civilman628** [shenweichen/DeepCTR#139]
**Describe the bug(问题描述)**
在movielens_samples.txt 数据集里面 genres 这个变长类别至少有一个值。但是在实际应用中，这类multi-label的类别很可能全都是空，比如部分数据未能采集到，也就是需要支持 全是0 的 变长标签：[0,0,0,0,0,0,0,0] 。这在采集数据创建训练集和 在 生产环境里predict时非常常见 。

**To Reproduce(复现步骤)**
1. 打开 movielens数据集。copy 第一行，复制到下一行。
3299,235,4,968035345,Ed Wood (1994), **Comedy|Drama** ,F,25,4,19119
2. 删除  **Comedy|Drama**，让genres 出现空值
3. 运行 **run_multivalue_movielens.py**
4. See error：
```
File "C:\Users\abc\source\repos\DeepCTR\examples\run_multivalue_movielens_local_test.py", line 12, in split
    key_ans = x.split('|')
AttributeError: 'float' object has no attribute 'split'
```

**Operating environment(运行环境):**
 - python version 3.7
 - tensorflow version 1.4
 - deepctr version [e.g. 0.5.2,]

**Additional context**

**Comment by zanshuxun** [comment]
这也不是all 0啊，是直接缺失了。需要用默认值填充一下
