### ISSUE TITLE
 TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

### ISSUE THREAD

**Issue by Jie-Yuan** [shenweichen/DeepCTR#14]
TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

**Comment by shenweichen** [comment]
Hi @Jie-Yuan You can download the latest version through `pip install  -U deepctr`,the bug is fixed and now deepctr supports tensorflow version from `1.5.0-1.12.0` except for `1.7.*` and `1.8.*`
