### ISSUE TITLE
如何保存原始数据 (raw data) 和 用于模型输入数据 (encoding data) 的映射关系？

### ISSUE THREAD

**Issue by civilman628** [shenweichen/DeepCTR#140]
**Is your feature request related to a problem? Please describe.**
现在两个数据文件一个是广告数据集，一个是电影数据集。 原始数据被转化后分成训练和测试数据。比如电影数据集原始数据的age = 25 , 经过 lbe.fit_transform() 之后变成了 2，这个也叫encoding. 这个是建立在分析了整个数据之后确定的。但是在生产环境中需要predict的数据通常是非常离散的。那么在模型训练好并且deploy之后，如何快速地把需要predict 的原始数据进行transform 或者说encoding 然后传给模型里呢？ 这个对于sparse 和 multi-value  input 都非常重要. Dense input 是不是需要我现在不知道。

**Describe the solution you'd like**
映射关系应该可以保存，实现快速查找表。

**Comment by civilman628** [comment]
找到了一个解决方案， 不知道 有没有 更好的 。PKL 不是一个很好的格式 。思路就是先把映射关系保存下来，在之后的预测再加载。

https://www.cnblogs.com/bonelee/p/10861506.html

https://stackoverflow.com/questions/28656736/using-scikits-labelencoder-correctly-across-multiple-programs

**Comment by Jie-Yuan** [comment]
> **Is your feature request related to a problem? Please describe.**
> 现在两个数据文件一个是广告数据集，一个是电影数据集。 原始数据被转化后分成训练和测试数据。比如电影数据集原始数据的age = 25 , 经过 lbe.fit_transform() 之后变成了 2，这个也叫encoding. 这个是建立在分析了整个数据之后确定的。但是在生产环境中需要predict的数据通常是非常离散的。那么在模型训练好并且deploy之后，如何快速地把需要predict 的原始数据进行transform 或者说encoding 然后传给模型里呢？ 这个对于sparse 和 multi-value input 都非常重要. Dense input 是不是需要我现在不知道。
> 
> **Describe the solution you'd like**
> 映射关系应该可以保存，实现快速查找表。

Hash Encoder

**Comment by chen849157649** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > 现在两个数据文件一个是广告数据集，一个是电影数据集。 原始数据被转化后分成训练和测试数据。比如电影数据集原始数据的age = 25 , 经过 lbe.fit_transform() 之后变成了 2，这个也叫encoding. 这个是建立在分析了整个数据之后确定的。但是在生产环境中需要predict的数据通常是非常离散的。那么在模型训练好并且deploy之后，如何快速地把需要predict 的原始数据进行transform 或者说encoding 然后传给模型里呢？ 这个对于sparse 和 multi-value input 都非常重要. Dense input 是不是需要我现在不知道。
> > **Describe the solution you'd like**
> > 映射关系应该可以保存，实现快速查找表。
> 
> Hash Encoder

@Jie-Yuan ，你好，Hash Encoder, 同样的字符串两次hash后结果不一样，需要自己定义哈希函数吧，如果依然使用deepctr, 只需要将labelencoder 换为hashencoder就可以了吗？谢谢

**Comment by zanshuxun** [comment]
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.inverse_transform
