### ISSUE TITLE
DeepFM里linear_logit和最后的PredictionLayer重复使用了bias

### ISSUE THREAD

**Issue by lonewar** [shenweichen/DeepCTR#150]
**Describe the bug(问题描述)**

DeepFM函数里调用了get_linear_logit，它调用的Linear方法里有bias。
DeepFM里最后调用了PredictionLayer类，默认的use_bias=True，所以用了两个bias。

**Comment by shenweichen** [comment]
thanks, it has been fixed in v0.6.3
