### ISSUE TITLE
java调用模型的问题

### ISSUE THREAD

**Issue by sunjiadong** [shenweichen/DeepCTR#162]
fit之后的模型保存为h5格式文件，转为Pb格式之后，java调用模型的话如何做预测呢？原来的predict不能用了吧？

**Comment by CapSOSkw** [comment]
请问下，怎么从h5转到pb格式？我转的过程一直报错，可以的话能分享下转换代码么？谢谢！

**Comment by whk6688** [comment]
您最后是怎么解决的呢

**Comment by JWenBin** [comment]
DeepMatch当前最新版本我这边无法导出pb模型格式，deepctr还没试过，Java或者scala调用的话，用这个：https://github.com/tensorflow/java

**Comment by duankai** [comment]
> DeepMatch当前最新版本我这边无法导出pb模型格式，deepctr还没试过，Java或者scala调用的话，用这个：https://github.com/tensorflow/java

如果都是tf.keras.model 的模型，应该都是可以的
