### ISSUE TITLE
Why is the parameter for the embedding size not present in case of fibinet?

### ISSUE THREAD

**Issue by rajeshshrestha** [shenweichen/DeepCTR#164]
I don't see options to change the embedding size in fibinet.
**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.13.1,]
 - deepctr version [e.g. 0.6.2,]

**Comment by shenweichen** [comment]
@Rajesh45npt  hi,if your`deepctr`  version is 0.7.0+(use `pip list` to check your version),the embedding size is set by specifying `embedding_dim` in `SparseFeat` or `VarLenSparseFeat `.
https://github.com/shenweichen/DeepCTR/blob/db229dc31f0d4c79c0de2ece0bb919b35258d6b2/examples/run_classification_criteo.py#L28

**Comment by Rajesh45npt** [comment]
@shenweichen I think this functionality has been added in version 0.7.0. Is there some option to set the embedding to fibinet in case of v0.6.2.? Also, could you clarify the difference in the embedding size present in most of the models like NFFM and the embedding size passed to the SparseFeat?
