### ISSUE TITLE
为啥保存个模型要半小时，模型大小只有不到10m

### ISSUE THREAD

**Issue by yyy1987** [shenweichen/DeepCTR#177]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.5.2,]

**Comment by shenweichen** [comment]
请尝试只保存模型的权重参数
```python
model = DeepFM()
model.save_weights('DeepFM_w.h5')
model.load_weights('DeepFM_w.h5')
```

**Comment by zanshuxun** [comment]
是怎么保存的？多久保存一次？
