### ISSUE TITLE
Linear logit in DeepFM - embedding dim

### ISSUE THREAD

**Issue by ornellamarciano** [shenweichen/DeepCTR#178]
In your last commit, you refactored feature columns which are now able to have a different "embedding dim" for each one.  You define now the "embedding dim" in the SparseFeat object. But then, in your example "run_classification_criteo", you are using the same SparseFeat objects for both the linear_feature_columns and dnn_feature_columns. It means that both parts have the same embedding dim, whereas for the linear logit, I am expected to get an embedding dim of 1 for each features. 
Can you have a look ?
Thanks

**Comment by shenweichen** [comment]
Hi ornellamarciano ,sorry for late reply.
You are right and I will clarify and fix this problem in the next version.

**Comment by bachephysicdun** [comment]
I faced similar issue with the "Classification: Criteo" and the embedding dim. 
If in this example (https://deepctr-doc.readthedocs.io/en/latest/Examples.html), the part that you defined `fixlen_feature_columns`, if I change the `embedding_dim=4` to `embedding_dim=min(50, round(len(data[feat].unique())))` 
I'll get the following error by DeepFM:

`A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 1, 27), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 12), (None, 1, 7), (None, 1, 50), (None, 1, 19), (None, 1, 2), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 14), (None, 1, 50), (None, 1, 50), (None, 1, 9), (None, 1, 50), (None, 1, 44), (None, 1, 4), (None, 1, 50), (None, 1, 6), (None, 1, 10), (None, 1, 50), (None, 1, 20), (None, 1, 50)]`

I expected that we can define an embedding_dim for each feature as each feature has different number of unique values. 
Could you please have a look?
Thanks
