### ISSUE TITLE
Training the DeepFM fails if we choose different embedding_dim for each feature ...

### ISSUE THREAD

**Issue by bachephysicdun** [shenweichen/DeepCTR#184]
I faced an issue with the "Classification: Criteo" example and the embedding_dim. 
In this example (https://deepctr-doc.readthedocs.io/en/latest/Examples.html), the part that you defined `fixlen_feature_columns`, if I change the `embedding_dim=4` to `embedding_dim=min(50, round(len(data[feat].unique())))` 
I'll get the following error by DeepFM:

`A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 1, 27), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 12), (None, 1, 7), (None, 1, 50), (None, 1, 19), (None, 1, 2), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 50), (None, 1, 14), (None, 1, 50), (None, 1, 50), (None, 1, 9), (None, 1, 50), (None, 1, 44), (None, 1, 4), (None, 1, 50), (None, 1, 6), (None, 1, 10), (None, 1, 50), (None, 1, 20), (None, 1, 50)]`

I expected that we can define an embedding_dim for each feature as each feature has different number of unique values. 

Could you please have a look?
Thanks

**Comment by shenweichen** [comment]
features that do two-order interactions must have same `embedding_dim` in `FM` part of `DeepFM`.

you can use inner-group feature interactions by setting the `group_name` in `SparseFeat`.

for example, if you have 6 features a,b,c,d,e,f.
- a,b,c have same embedding_dim `embedding_dim=4,group_name='group1'` 
- d,e,f have same  embedding_dim `embedding_dim=8,group_name='group2'`,

**Comment by bachephysicdun** [comment]
Thanks!

**Comment by bachephysicdun** [comment]
Thanks!
