### ISSUE TITLE
What's the feature "item_gender" in DIN / DIEN? 

### ISSUE THREAD

**Issue by Curlykonda** [shenweichen/DeepCTR#187]
**Describe the question(问题描述)**
What does the feature column with the name `item_gender` represent? Is it an indication of click/not-clicked corresponding to the item at that position? 

If so, why do we have a vocabulary size of `2+1`? Why should we record items in the history that were not clicked? 

**Additional context**
In the example run-files `run_din.py` and run_dien.py the sparse features `hist_item_gender` are added to the feature columns together with `hist_item`. 

**Operating environment(运行环境):**
 - deepctr version [e.g. 0.7.1,]

**Comment by shenweichen** [comment]
`item_gender` means which gender(male or female) will prefer this item more.`2+1`,2 is for male and female,1 is for missing value
