### ISSUE TITLE
训练从第二个epoch开始后面的loss不变，是什么原因？

### ISSUE THREAD

**Issue by HelloWorld19930113** [shenweichen/DeepCTR#193]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.7.1,]

**Comment by HelloWorld19930113** [comment]
应该是数据问题，但是不知道从哪里开始查找

**Comment by shenweichen** [comment]
@HelloWorld19930113 也有可能是一个epoch模型就收敛了，后面继续训练开始过拟合了

**Comment by guotong1988** [comment]
同问
