### ISSUE TITLE
DIEN报错ValueError: The name "seq_length" is used in 2 times in the model. All layer names should be unique.

### ISSUE THREAD

**Issue by MildAdam** [shenweichen/DeepCTR#200]
**Describe the bug(问题描述)**
运行run_dien.py时，报错ValueError: The name "seq_length" is used in 2 times in the model. All layer names should be unique.

**To Reproduce(复现步骤)**
1. 运行examples/run_dien.py
2. See error

**Operating environment(运行环境):**
 - python version [3.7.4]
 - tensorflow version [2.0.0]
 - deepctr version [0.7.4]

**Additional context**

**Comment by zhenglinghan** [comment]
请问解决了嘛

**Comment by zhenglinghan** [comment]
tf 版本问题

**Comment by gjq718** [comment]
我也遇到这个问题了，请问您是怎么解决的

**Comment by zhenglinghan** [comment]
主要是tensorflow版本问题 建议升级tensorflow版本 至少1.14吧好像 2.x肯定是没问题的




--

郑凌瀚 风险量化部
zhenglinghan@dycjr.com
公司名称：宝德融资租赁（上海）有限公司
地址：上海市浦东新区福山路388号越秀大厦501室
电话：021-50773202
手机：





发件人：gjq718 <notifications@github.com>
发送日期：2020-08-13 16:36:31
收件人：shenweichen/DeepCTR <DeepCTR@noreply.github.com>
抄送人："阿郑zzz" <zhenglinghan@dycjr.com>,Comment <comment@noreply.github.com>
主题：Re: [shenweichen/DeepCTR] DIEN报错ValueError: The name "seq_length" is used in 2 times in the model. All layer names should be unique. (#200)

我也遇到这个问题了，请问您是怎么解决的

**Comment by gjq718** [comment]
> 主要是tensorflow版本问题 建议升级tensorflow版本 至少1.14吧好像 2.x肯定是没问题的
> […](#)
> -- 郑凌瀚 风险量化部 zhenglinghan@dycjr.com 公司名称：宝德融资租赁（上海）有限公司 地址：上海市浦东新区福山路388号越秀大厦501室 电话：021-50773202 手机： 发件人：gjq718 <notifications@github.com> 发送日期：2020-08-13 16:36:31 收件人：shenweichen/DeepCTR <DeepCTR@noreply.github.com> 抄送人："阿郑zzz" <zhenglinghan@dycjr.com>,Comment <comment@noreply.github.com> 主题：Re: [shenweichen/DeepCTR] DIEN报错ValueError: The name "seq_length" is used in 2 times in the model. All layer names should be unique. (#200) 我也遇到这个问题了，请问您是怎么解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我的是2.0.0版本

**Comment by gjq718** [comment]
2.0.0版本出现了这个问题

**Comment by shenweichen** [comment]
请升级deepctr到最新版本
