### ISSUE TITLE
Where to download the criteo_sample.txt?

### ISSUE THREAD

**Issue by vba34520** [shenweichen/DeepCTR#201]
**Describe the question(问题描述)**
Where to download the criteo_sample.txt?
I have download datasets from the website below but the dataset is not correct:
1. [Download Kaggle Display Advertising Challenge Dataset - Criteo Labs](http://labs.criteo.com/2014/02/download-kaggle-display-advertising-challenge-dataset/) is about 4.26GB.
2. [Display Advertising Challenge | Kaggle](https://www.kaggle.com/c/criteo-display-ad-challenge/) is about 47.5MB but just a random_submission.csv.

Would you please share your dataset? Thanks a lot.

**Comment by shenweichen** [comment]
https://github.com/shenweichen/DeepCTR/blob/master/examples/criteo_sample.txt

**Comment by vba34520** [comment]
Thank you so much, good day!
