### ISSUE TITLE
cannot import name 'get_fixlen_feature_names' from 'deepctr.inputs

### ISSUE THREAD

**Issue by YutingSun163** [shenweichen/DeepCTR#202]
你好，from deepctr.inputs import get_fixlen_feature_names报错了，cannot import name 'get_fixlen_feature_names' from 'deepctr.inputs。然后我在官网上deepctr的所有模块手动查找了这个函数也没有找到，请问是什么问题呢？

 - python version [. 3.7]
 - deepctr version [0.7.4,]

**Comment by shenweichen** [comment]
这个函数是历史版本中的，现在已经没有了。可以参考下最新的文档 https://deepctr-doc.readthedocs.io/en/latest/Examples.html
