### ISSUE TITLE
你这个模型在进行推理的时候性能很差，不知道是什么原因

### ISSUE THREAD

**Issue by rickyhuw** [shenweichen/DeepCTR#203]
**Describe the question(问题描述)**
在使用deepfm模型进行推理时，单次推理达到300ms，这么高的延迟，不知道是我的操作原因，还是框架本身的问题，在给的例子中进行测试，也得到了相同的结论，如果有解决办法请告知一下，非常感谢！

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 2.1.0,]
 - deepctr version [e.g. 0.7.4,]

**Comment by LYJ-LiYujian** [comment]
同问！单次请求延迟在200-300ms，QPS很难上去，不知道该怎么调整

**Comment by DachuanZhao** [comment]
> **Describe the question(问题描述)**
> 在使用deepfm模型进行推理时，单次推理达到300ms，这么高的延迟，不知道是我的操作原因，还是框架本身的问题，在给的例子中进行测试，也得到了相同的结论，如果有解决办法请告知一下，非常感谢！
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Operating environment(运行环境):**
> 
> * python version [e.g. 3.6]
> * tensorflow version [e.g. 2.1.0,]
> * deepctr version [e.g. 0.7.4,]

为什么不上tf-serving?

**Comment by leidaxia** [comment]
m

**Comment by guotong1988** [comment]
m

**Comment by wertyou** [comment]
+1

**Comment by rickyhuw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已被接受，我将尽快回复您！

**Comment by rickyhuw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已被接受，我将尽快回复您！
