### ISSUE TITLE
如何在现有tf-gpu版本基础上安装deepctr

### ISSUE THREAD

**Issue by shm007g** [shenweichen/DeepCTR#207]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
如何在已有的tensorflow-gpu 1.11基础上直接安装deepctr[gpu]，暂时没有升级tf-gpu到2.0+的打算。我看一安装就是2.1的。

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.11.0,]
 - deepctr version [e.g. 0.7.1,]

**Comment by shenweichen** [comment]
先安装tf-gpu 1.11 `pip install tensorflow-gpu==1.11.0`
然后运行命令`pip install -U deepctr`注意没有`[gpu]`后缀，就可以保留原来版本的tf
