### ISSUE TITLE
about auto embedding size

### ISSUE THREAD

**Issue by NemoSailingHeart** [shenweichen/DeepCTR#215]
您好请问一下关于embedding size设置为auto时 ，size= 6 * int(pow(vocabulary_size, 0.25))，这个公式是有什么理论支持么？还是经验值

**Comment by shenweichen** [comment]
来自Google的论文《Deep & Cross Network for Ad Click Predictions》
![image](https://user-images.githubusercontent.com/18311786/81537123-4bdbca80-939f-11ea-828e-4e50d6c73d90.png)
