### ISSUE TITLE
把DeepFM改成CCPM，报错DenseFeat is not supported in dnn_feature_columns

### ISSUE THREAD

**Issue by jc-moon** [shenweichen/DeepCTR#220]
如题，原先DeepFM运行一切正常，改成CCPM之后，看API好像是类似的
但这行就会报错
`model = CCPM(linear_feature_columns, dnn_feature_columns, task='binary')`
ValueError: DenseFeat is not supported in dnn_feature_columns

**Comment by shenweichen** [comment]
看下提示信息：CCPM暂时不支持`DenseFeat`
