### ISSUE TITLE
supporting pretrain embedding ?

### ISSUE THREAD

**Issue by lsq357** [shenweichen/DeepCTR#221]
貌似sparseFeat 里没有加载预训练的向量，embedding layer 都是随机初始化

**Comment by shenweichen** [comment]
支持的，目前需要通过自己获取到对应layer然后为layer的embedding矩阵赋值来实现，后续会提供简单的api给大家，可以先参考这个获取embedding向量的链接 
https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-extract-the-embedding-vectors-in-deepfm
