### ISSUE TITLE
训练DeepFM时指定了loss，但是没有用。

### ISSUE THREAD

**Issue by elzizyel** [shenweichen/DeepCTR#223]
问题描述:
在compile里已经指定了loss与metrics均为'binary_crossentropy'，但是训练时出来的loss与binary_crossentropy不一致。

运行环境:
 - python version 3.6.5
 - tensorflow version 2.0.0
 - deepctr version 0.7.5

![376390D5-BE8D-4E85-B438-0DA9BD77F5A4](https://user-images.githubusercontent.com/42927184/83721726-38561380-a66e-11ea-957a-631b9fd6ffcd.png)

**Comment by shenweichen** [comment]
这两个本来就不是一个哈,loss是带有正则项的

**Comment by elzizyel** [comment]
> 这两个本来就不是一个哈,loss是带有正则项的

诶，我的意思是我在compile里面已经指定了使用'binary_crossentropy'作为loss来训练模型，为什么在fit模型的时候，log里面出现的loss不是'binary_crossentropy'呢？
另外，这个带正则项的loss是啥呀？

**Comment by zanshuxun** [comment]
您是不知道正则项是啥意思吗
