### ISSUE TITLE
加载保存好的模型  然后预测返回的结果 全是 nan

### ISSUE THREAD

**Issue by miaochaowei** [shenweichen/DeepCTR#224]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
加载保存好的模型  然后预测返回的结果 全是 nan  请教一下什么问题

**Additional context**

**Operating environment(运行环境):**
 - python version  3.6
 - tensorflow version 2.2
 - deepctr version  0.74

**Comment by shenweichen** [comment]
先测试下tf.1.x版本是否存在该问题？

**Comment by miaochaowei** [comment]
找到了  特征中 有nan
