### ISSUE TITLE
加载模型后，预测结果都是0

### ISSUE THREAD

**Issue by rickyhuw** [shenweichen/DeepCTR#226]
模型训练的输出结果都偏小0.5以内，加载模型后预测结果都是0，或者都是1

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.7.1,]

**Comment by zanshuxun** [comment]
正负样本比例多少？

**Comment by guotong1988** [comment]
楼主解决了没
