### ISSUE TITLE
关于FLEN模型的问题

### ISSUE THREAD

**Issue by diwuxiaoxu** [shenweichen/DeepCTR#228]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
ValueError: A `Field-Wise Bi-Interaction` layer should be called on a list of at least 2 inputs

**Additional context**
使用的是examples/run_classification_criteo.py，调用FLEN模型，其它部分未修改，出现上述错误，请问如何修改

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.7.1,]

**Comment by TanTingyi** [comment]
FLEN 模型需要指定特征的场信息，尽管不推荐将 FLEN 用在匿名特征的例子上，但是你可以通过以下的方式适当修改以使的模型可以顺利运行。
```python
field_info` = ['user'] * 10 + ['item'] * 17
# 添加场信息
fixlen_feature_columns = [
    SparseFeat(feat,
                vocabulary_size=data[feat].nunique(),
                embedding_dim=4,
                group_name=field_info[i])
    for i, feat in enumerate(sparse_features)
] + [DenseFeat(
    feat,
    1,
) for feat in dense_features]
```
