### ISSUE TITLE
稀疏编码one-hot保持一致性

### ISSUE THREAD

**Issue by aiot-tech** [shenweichen/DeepCTR#231]
你好，非常感谢提供这么棒的代码包，使用的过程中也是非常的顺畅！只是有一个小问题是，如果trian和test两个数据集是分离的，我该怎么做才能保证稀疏特征在两个训练集上是一样的呢，比如train集上，1的one-hot是[0,0,0,1],test中1的one-hot如果不一致的话，就有可能是[1,0,0,0]了

**Comment by shenweichen** [comment]
test中为出现的可以统一赋值为缺失值编码。另外一种就是考虑对输入的id进行哈希处理映射到同一个空间下

**Comment by aiot-tech** [comment]
我看源码的时候，有点不理解的是，代码中好像没有处理这种情况？
##examples/run_classification_criteo.py  
```
# 1.Label Encoding for sparse features,and do simple Transformation for dense features
for feat in sparse_features:
    lbe = LabelEncoder()
    data[feat] = lbe.fit_transform(data[feat])
```
假定data是train集，那么这里的lbe对新的test集进行LabelEncoder时，会不会出现同一个元素，得到的编码是不一样的？

**Comment by Florawfx** [comment]
做一个feature 和 LabelEncoder的映射吧, 然后处理 test集的时候, 用train集生成的LabelEncoder 生成one-hot 编码,应该可以吧, 参考 https://zhuanlan.zhihu.com/p/107752696

**Comment by aiot-tech** [comment]
好的，谢谢啦，我去试一下
