### ISSUE TITLE
训练时正常，predict报错

### ISSUE THREAD

**Issue by ThanatosXPF** [shenweichen/DeepCTR#25]
model.fit()能正常运行但是在进行预测时候报错，请问有能正常运行model.predict()或者model.predict_on_batch()的example吗
'''
   output = model.predict(model_output, batch_size=256, verbose=0, steps=None)
'''
报错：
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[139, 0] = 28 is not in [0, 27]

**Comment by shenweichen** [comment]
@ThanatosXPF 您好，感谢使用，您的这个情况是由于预测的时候样本中出现的特征索引超出了预定义的Embedding字典的范围，建议您在进行feature config的时候考虑上测试集合的样本，或者使用哈希编码的方式将所有特征映射到一个定长的空间。`predict`和`predict_on_batch`方法本身应该是没有问题的。
您可以简单运行下下面的例子：
```python
import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from deepctr.models import DeepFM


data = pd.read_csv('./examples/criteo_sample.txt')

sparse_features  = ['C' + str(i) for i in range(1, 27)]
dense_features = ['I'+str(i) for i in range(1,14)]

data[sparse_features] = data[sparse_features].fillna('-1', )
data[dense_features] = data[dense_features].fillna(0,)

target = ['label']

# 1.Label Encoding for sparse features,and do simple Transformation for dense features
for feat in sparse_features:
    lbe = LabelEncoder()
    data[feat] = lbe.fit_transform(data[feat])
mms = MinMaxScaler(feature_range=(0,1))
data[dense_features] = mms.fit_transform(data[dense_features])

# 2.count #unique features for each sparse field,and record dense feature field name

sparse_feature_dict = {feat: data[feat].nunique() for feat in sparse_features}
dense_feature_list = dense_features

# 3.generate input data for model

model_input = [data[feat].values for feat in sparse_feature_dict] + [data[feat].values for feat in dense_feature_list]

#4.Define Model,compile and train


model = DeepFM({"sparse": sparse_feature_dict, "dense": dense_feature_list}, final_activation='sigmoid')
model.compile("adam", "binary_crossentropy", metrics=['binary_crossentropy'], )
history = model.fit(model_input, data[target].values,
                    batch_size=256, epochs=1, verbose=2, validation_split=0.2,)
# prediction
pred_ans = model.predict(model_input,batch_size=256)
pred_batch = model.predict_on_batch(model_input)
print("prediction done")
```

希望能解决你的问题~

**Comment by daisy-belle** [comment]
@shenweichen 您好，我运行run_regression_movielens.py这个文件的时候，第一次运行正确没有问题，保持全部一样接着运行第二次就会报上面同样的错误
第一次结果：
WARNING:tensorflow:From C:\work\project\learn_test\DeepCTR-master\deepctr\layers.py:411: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-01-23 10:47:09.156000: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Train on 128 samples, validate on 32 samples
Epoch 1/1
 - 1s - loss: 13.5552 - mean_squared_error: 13.5552 - val_loss: 15.7727 - val_mean_squared_error: 15.7727
test MSE 14.5247

Process finished with exit code 0

第二次报错结果：
Epoch 1/1
Traceback (most recent call last):
  File "C:/work/project/learn_test/DeepCTR-master/examples/run_regression_movielens.py", line 31, in <module>
    batch_size=256, epochs=1, verbose=2, validation_split=0.2,)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 86 is not in [0, 7)
	 [[{{node linear_emb_4-age/embedding_lookup}} = ResourceGather[Tindices=DT_INT32, _class=["loc:@training/Adam/gradients/linear_emb_4-age/embedding_lookup_grad/Reshape"], dtype=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](linear_emb_4-age/embeddings, sparse_emb_4-age/Cast)]]

Process finished with exit code 1
而且是同样的数据，这个还会是特征索引超出了预定义的Embedding字典的范围的问题吗？

**Comment by shenweichen** [comment]
@daisy-belle 您好，请问您是怎么运行第二次的？是通过
```bash
$  python .\run_regression_movielens.py
```
命令吗？两次程序运行应该是互不影响的

**Comment by daisy-belle** [comment]
@shenweichen 我是在windows环境下使用pycharm IDE 运行的，两次都是，一次运行完后什么都不改变接着运行第二次，就出现了上述那个问题

**Comment by shenweichen** [comment]
@daisy-belle 我用pycharm试了一下没有问题呀....你试试用命令行运行两次...

**Comment by daisy-belle** [comment]
@shenweichen 嗯呀，我刚又试了一下，两次串行运行确实是没问题的，不过当运行第一个还没运行完，接着运行第二个才会出现上面的错误。开始的时候没注意以为第一次已经运行完了😂
