### ISSUE TITLE
How to get prediction result with identification information(e.g. ID)?

### ISSUE THREAD

**Issue by hibayesian** [shenweichen/DeepCTR#250]
**Describe the question(问题描述)**
How to get prediction result with identification information(e.g. ID)? I think it's a very common scenario we want to know each prediction belongs to whom(e.g user id). I have no idea how to implement this in DeepCTR.

**Operating environment(运行环境):**
 - deepctr version [e.g. 0.8.0,]

**Comment by zanshuxun** [comment]
each prediction corresponding to a input sample, which usually contains the userid and itemid
