### ISSUE TITLE
 deepfm.py     ValueError: '_emb_feature' is not a valid scope name

### ISSUE THREAD

**Issue by Sue52nlp** [shenweichen/DeepCTR#256]
**ValueError: '_emb_feature' is not a valid scope name** 

deepfm.py中
group_embedding_dict, dense_value_list = input_from_feature_columns(features, dnn_feature_columns, l2_reg_embedding,seed, support_group=True) 
未对prefix进行赋值，会默认prefix=''

input_from_feature_columns 中调用了 create_embedding_matrix ，
create_embedding_matrix中
emb = Embedding(feat.vocabulary_size, feat.embedding_dim,
                        embeddings_initializer=feat.embeddings_initializer,
                        embeddings_regularizer=l2(l2_reg),
                        name=prefix + '_emb_' + feat.embedding_name)

如果input_from_feature_columns中prefix不进行赋值，会出现报错ValueError: '_emb_feature' is not a valid scope name

**Comment by zanshuxun** [comment]
> 如果input_from_feature_columns中prefix不进行赋值，会出现报错ValueError: '_emb_feature' is not a valid scope name

我试了一下，input_from_feature_columns中的prefix不进行赋值也可以跑通（默认就是不进行赋值），无法复现这个报错。可以给出复现步骤吗？
