### ISSUE TITLE
请问下DeepFM如何实现为每个用户推荐物品列表？

### ISSUE THREAD

**Issue by Robbieing** [shenweichen/DeepCTR#257]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.2.0]
 - deepctr version [e.g. 0.8.0,]

**Comment by shenweichen** [comment]
取打分最高的topN
