### ISSUE TITLE
SparseFeat函数的embedding_dim设为'auto'时报错

### ISSUE THREAD

**Issue by linmengnan** [shenweichen/DeepCTR#260]
您好，当我sparse feature的embedding_dim设定为'auto'时，如下
** sparse_feature_columns = [SparseFeat(feat, vocabulary_size=(all_Data.nunique(),embedding_dim='auto')
                                                             for i,feat in enumerate(sparse_features)]

运行后，报错：
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 1, 16), (None, 1, 32), (None, 1, 6), (None, 1, 42)]

当embedding_dim为定值时，可以正常运行，请问该怎么解决这个问题？

**Comment by shenweichen** [comment]
一些模型要求所有`embedding_dim`保持一致，所以设置`auto`会报错，建议先阅读论文了解算法原理
