### ISSUE TITLE
PNN InnerProductLayer & OutterProductLayer中构建p、q逻辑错误

### ISSUE THREAD

**Issue by Yang-Lv** [shenweichen/DeepCTR#264]
**Describe the bug(问题描述)**
PNN InnerProductLayer & OutterProductLayer中构建p、q逻辑错误。

**To Reproduce(复现步骤)**
![image](https://user-images.githubusercontent.com/13713038/89632319-943e5200-d8d4-11ea-9a88-342aefc77221.png)
应该用tf.stack(x,axis=1)
建议：把变量结构写清楚，多加一些注释

**Operating environment(运行环境):**
 - python version 2.7
 - tensorflow version 1.14
 - deepctr version 0.8

**Comment by shenweichen** [comment]
请仔细阅读论文和代码

**Comment by TangJiakai** [comment]
因为这里输入shape是(b,1,k)，所以cat在axis=1才对。不过我这里也有疑问，InnerProductLayer这里实现只是输出一个l_p（shape是b,1），应该这样的操作重复D次，然后每次输出concat起来(得到shape为b,d)。OutterProduct也是一样，这样才符合原文？
