### ISSUE TITLE
 lbe = HashEncoder()

### ISSUE THREAD

**Issue by chen849157649** [shenweichen/DeepCTR#266]
HashEncoder()哪个包导入的，
for feat in sparse_features:
    lbe = HashEncoder()
    data[feat] = lbe.transform(data[feat])
同样的字符串两次编码后值相同吗？，此方法在预测时能否使用？望解答，谢谢老师

**Comment by shenweichen** [comment]
HashEncoder()只是一个例子，并不是一个具体的函数。
deepctr里也有提供这个功能，在定义`SparseFeat`时设置`use_hash=True`就可以。具体的可以参考文档
https://deepctr-doc.readthedocs.io/en/latest/Features.html#sparsefeat
