### ISSUE TITLE
AttentionSequencePoolingLayer类，call()中未传递mask参数。

### ISSUE THREAD

**Issue by codefish1990** [shenweichen/DeepCTR#267]
AttentionSequencePoolingLayer类，call()中未传递mask参数，但是打印mask，显示是两个tensor的list，求教是哪传递进来的？

**Comment by 631763140** [comment]
query_emb, keys_emb里面带的，用keys_emb._keras_mask输出看看

**Comment by ninesky110** [comment]
![image](https://user-images.githubusercontent.com/38121533/101750364-dd641400-3b09-11eb-9831-42b13cef7df2.png)
没带啊

**Comment by zanshuxun** [comment]
> ![image](https://user-images.githubusercontent.com/38121533/101750364-dd641400-3b09-11eb-9831-42b13cef7df2.png)
> 没带啊

所以我上面那句话你是只看了前半句吗。。。

**Comment by ninesky110** [comment]
> > ![image](https://user-images.githubusercontent.com/38121533/101750364-dd641400-3b09-11eb-9831-42b13cef7df2.png)
> > 没带啊
> 
> 所以我上面那句话你是只看了前半句吗。。。
![image](https://user-images.githubusercontent.com/38121533/101764033-8b77ba00-3b1a-11eb-9687-dfa889560c2e.png)

什么叫keys_emb里面带，这个call函数的传参一个是input（query_emb, keys_emb），还有一个是mask。keys_emb和mask有关系吗？

**Comment by zanshuxun** [comment]
你先把我后半句话照做了
