### ISSUE TITLE
How to extract the embedding vectors in deepfm?

### ISSUE THREAD

**Issue by LMdeLiangMi** [shenweichen/DeepCTR#27]
**Describe the question(问题描述)**
I want to get the embedding vectors of deepfm and use them as inputs of other models, like this:
https://github.com/jfpuget/LibFM_in_Keras/blob/master/keras_blog.ipynb

**Additional context**

**Comment by shenweichen** [comment]
@LMdeLiangMi Hi,in `deepctr v0.2.2`,you can get the embedding vectors of sparse features with the following codes
```python
fd = {"sparse":{'uid':10000,'itemid':888},'dense':[]}
def get_embedding_weights(feature_dim_dict,model):
    return {feat: model.get_layer("sparse_emb_"+str(i)+'-'+feat).get_weights()[0] for i, feat in enumerate(feature_dim_dict["sparse"])}
embedding_dict = get_embedding_weights(fd,model)
uid_emb = embedding_dict['uid']
itemid_emb = embedding_dict['itemid']
```
`uid_emb[i,:]` is the embedding vector of field `uid` with `feature_value=i`

**Comment by LMdeLiangMi** [comment]
Thanks a lot!
