### ISSUE TITLE
损失函数

### ISSUE THREAD

**Issue by diwuxiaoxu** [shenweichen/DeepCTR#277]
**Describe the bug(问题描述)**
A clear and concise description of what the bug is. 您好， 在DeepFM模型上，跑criteo数据集，数据集十万条，其它参数没变，跑出来的logloss大于1，请问是什么问题？

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.7] 3.5
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.2.0] 1.14.0
 - deepctr version [e.g. 0.8.0,] 0.7.5

**Additional context**

**Comment by zanshuxun** [comment]
您好 可以发一下训练日志看看吗

**Comment by diwuxiaoxu** [comment]
感谢您的回信，问题已经解决。
