### ISSUE TITLE
Converting sparse IndexedSlices to a dense Tensor of unknown shape.  This may consume a large amount of memory

### ISSUE THREAD

**Issue by Mesilenceki** [shenweichen/DeepCTR#278]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
在用deepmatch训练的时候，会碰到这个，看了网上类似的issue，都是很大可能会导致OOM，主要是在于tf.nn.embedding_lookup和tf.gather操作，请问有什么好的解决办法吗

**Additional context**

**Operating environment(运行环境):**
 - python version 3.6 - tensorflow version 2.0.0
 - deepctr version 0.7.8

**Comment by zanshuxun** [comment]
跑的哪个模型？可以给出复现步骤吗？
