### ISSUE TITLE
run_estimator_tfrecord_classification 不具有可复现性

### ISSUE THREAD

**Issue by luckmoon** [shenweichen/DeepCTR#287]
**Describe the bug(问题描述)**
run_estimator_tfrecord_classification 不具有可复现性

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version 3.6
 - tensorflow version 1.15.0
 - deepctr version 0.8.2

**Additional context**

**Comment by zanshuxun** [comment]
需要可复现性的话 可以在`RunConfig`中指定`tf_random_seed`来实现，例子如下：
```python
    # 3.Define Model,train,predict and evaluate
    config = tf.estimator.RunConfig(tf_random_seed=2020)
    model = DeepFMEstimator(linear_feature_columns, dnn_feature_columns, task='binary', config=config)
```
