### ISSUE TITLE
GPU out of memory with reasonable data

### ISSUE THREAD

**Issue by LiChen2012** [shenweichen/DeepCTR#29]
**Describe the bug(问题描述)**
I have a sparse feature with 1M items with 256 embedding. That is 1GB memory. "Adam" optimizor will need 2 more copies of GPU memories. So it is around 3GB. But it is still OOM on GPU with 8GB memory.
Is there any way to reduce GPU memory usage, like put some tensors on CPU instead?
Thanks.

**To Reproduce(复现步骤)**
1. The code:
import sys
import time
from deepctr.models import DeepFM
from deepctr import SingleFeat
if __name__ == '__main__':
    PIDCount = 1048576
    embedding_size = 256
    sparse_feature_list = [SingleFeat("PID", PIDCount)]
    dense_feature_list = [SingleFeat('AttrCS', 0)]
    model = DeepFM({"sparse": sparse_feature_list,
                    "dense": dense_feature_list}, embedding_size=embedding_size)
    model.compile("adam", "binary_crossentropy",
                  metrics=['binary_crossentropy'], )
    history = model.fit([[0], [0]], [[0]], epochs=1, verbose=2)
2. OOM for GPU
Summary of in-use Chunks by size: 
81 Chunks of size 256 totalling 20.2KiB
11 Chunks of size 512 totalling 5.5KiB
6 Chunks of size 1024 totalling 6.0KiB
1 Chunks of size 1280 totalling 1.2KiB
4 Chunks of size 65536 totalling 256.0KiB
4 Chunks of size 262144 totalling 1.00MiB
7 Chunks of size 4194304 totalling 28.00MiB
2 Chunks of size 4194560 totalling 8.00MiB
6 Chunks of size 1073741824 totalling 6.00GiB
Sum Total of in-use chunks: 6.04GiB
Stats: 
Limit:                  7440534733
InUse:                  6481544704
MaxInUse:               6481544704
NumAllocs:                     124
MaxAllocSize:           1073741824

**Comment by shenweichen** [comment]
@LiChen2012 

I  have successfully  ran the code snippet you provided on my laptop without GPU. Because it is a holiday now, I can't test the GPU version.
I don't know how to put some tensors or ops on CPU when using `tf.keras`,I think there are 2 methods you can try.
1. Modify the line 39 of`deepctr.models.deepfm` model like following:
```python
with tf.device("/cpu:0"):
    deep_emb_list, linear_logit, inputs_list = get_inputs_embedding(feature_dim_dict, embedding_size, l2_reg_embedding, l2_reg_linear, init_std, seed)
```
2. Reduce `embedding_size` dimension

**Comment by LiChen2012** [comment]
After modification of code, now GPU memory usage decreased. But it seems still not meet my expectations.
Before the fix, sparse feature embedding memory usage was 3 times of what should be.
After the fix, sparse feature embedding memory usage is double of what should be.
I hope you can take some time to fix it. Thanks.

**Comment by LiChen2012** [comment]
Another issue: 
After modification of code, training is slow. GPU usage jumps between 5% to 95%. I suspected that set tensor to CPU will cause memory copy between GPU and CPU. 
Thanks.

**Comment by shenweichen** [comment]
This solution puts the vector itself on the CPU, and the parameters created by the optimizer are still on the GPU, so there is still twice the memory usage.
I'm sorry that I don't have a perfect solution right now, and I think I need help from the community~
