### ISSUE TITLE
单机多卡训练问题

### ISSUE THREAD

**Issue by Mandule** [shenweichen/DeepCTR#291]
**Describe the bug(问题描述)**
在仿照examp 中单机多卡的训练方式时，使用 multi_gpu_model 的时候，提示我使用tf.distribute.MirroredStrategy来替代。无论我使用哪种方法都无法实现 单机多卡 训练，甚至会引起系统的崩溃。

**To Reproduce(复现步骤)**
1.
model = xDeepFM(..)
model = multi_gpu_model(model, gpus=4)
model.complie(...)
model.fit(....)
此时使用的还是单个GPU,并且提醒我要使用 tf.distribute.MirroredStrategy，因为multi_gpu_model 将在2020.4.1被移除
2. 
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = xDeepFM(..)
    model.complie(...)
model.fit(....)
此时使用的还是单个GPU

**Operating environment(运行环境):**
 - python 3.6
 - tensorflow version 2.0.0
 - deepctr version 0.8.2

**Comment by Mandule** [comment]
补充：multi_gpu_model 无法实现单机多卡，但是可以保证正常单卡运行。 tf.distribute.MirroredStrategy 直接导致无法运行

**Comment by guotong1988** [comment]
报什么错

**Comment by kinghuin** [comment]
> 补充：multi_gpu_model 无法实现单机多卡，但是可以保证正常单卡运行。 tf.distribute.MirroredStrategy 直接导致无法运行

执行tf.compat.v1.disable_eager_execution()，可以让multi_gpu_model实现单机多卡
