### ISSUE TITLE
没有sparse特征，只有dense特征时，DeepFMEstimator报错

### ISSUE THREAD

**Issue by Fanoid** [shenweichen/DeepCTR#295]
**Describe the bug(问题描述)**
DeepFMEstimator里，当没有sparse特征时，sparse_embedding_list为空，`concat_func(sparse_embedding_list, axis=1)`报错。

**Comment by shenweichen** [comment]
只有dense用普通的DNN就可以了，没有必要使用DeepFM，DeepFM的特性是高效进行sparse特征的二阶交叉组合
