### ISSUE TITLE
请问deepctr支持处理imbalanced数据集吗？怎么处理

### ISSUE THREAD

**Issue by jqsl2012** [shenweichen/DeepCTR#296]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.3.0]
 - deepctr version [e.g. 0.8.2,]

**Comment by MissZhou666** [comment]
> Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.
> 
> **Describe the question(问题描述)**
> A clear and concise description of what the question is.
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Operating environment(运行环境):**
> 
> * python version [e.g. 3.6]
> * tensorflow version [e.g. 1.4.0, 1.5.0, 2.3.0]
> * deepctr version [e.g. 0.8.2,]

    weight_for_0 = (1 / neg_cnt)*(all_cnt)/2.0
    weight_for_1 = (1 / pos_cnt)*(all_cnt)/2.0
    class_weight = {0: weight_for_0, 1: weight_for_1}
    history = model.fit(train_model_input, train[target].values,
                        batch_size=32768, epochs=100, verbose=2, validation_split=0.2, class_weight=class_weight)

**Comment by jqsl2012** [comment]
谢谢，已采用了这种方式。
