### ISSUE TITLE
关于DeepFM中Sparse特征的Embedding过程。

### ISSUE THREAD

**Issue by STHSF** [shenweichen/DeepCTR#298]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
DeepFM中输入的Sparse特征在Embedding之前需要对Category的field用one-hot展开，这个过程我没有在代码中找到， 可否提示一下，感谢。

**Comment by zanshuxun** [comment]
### 类别特征embedding的实现
有两种方式
1. 将原始类别特征转为onehot向量，再与embedding matrix相乘；
2. 将原始类别特征作为下标，直接从embedding matrix中取出对应行的向量。

这两种方式在数学上等价 且2复杂度更低 目前主流深度学习框架的实现都是2：

tf: https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/ops/embedding_ops.py#L333

> Looks up embeddings for the given `ids` from a list of tensors.

pytorch: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/sparse.py#L12

> This module is often used to store word embeddings and retrieve them using indices

### deepctr中的embedding
同样采用2，位置：
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/deepctr/models/deepfm.py#L49
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/deepctr/feature_column.py#L183
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/deepctr/inputs.py#L86-L88

**Comment by STHSF** [comment]
多谢，我消化一下
