### ISSUE TITLE
from deepctr import SingleFeat

### ISSUE THREAD

**Issue by CQuqumber** [shenweichen/DeepCTR#30]
I've installed the latest version deepctr, and when I import **SingFeat** and got the import error

`from deepctr import SingleFeat `

ImportError: cannot import name 'SingleFeat'

Packages Version：
tensorflow:1.12.0
keras:2.2.2
deepctr:0.2.3

OS: Ubuntu "16.04.5 LTS (Xenial Xerus)"

**Comment by shenweichen** [comment]
hi~@CQuqumber 
you can try
```python
from deepctr.utils import SingleFeat
```
