### ISSUE TITLE
[数据集下载] Criteo CTR prediction

### ISSUE THREAD

**Issue by huangbiubiu** [shenweichen/DeepCTR#308]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
很多模型都是使用Criteo Kaggle数据集训练的，但是现在看起来Criteo数据集的[下载链接](http://labs.criteo.com/2014/02/download-kaggle-display-advertising-challenge-dataset/)已经失效了。现在还有什么地方可以下载到Criteo数据集吗？

**Comment by zanshuxun** [comment]
试试从这里下载速度如何？
https://figshare.com/articles/dataset/Kaggle_Display_Advertising_Challenge_dataset/5732310

**Comment by huangbiubiu** [comment]
> 试试从这里下载速度如何？
> https://figshare.com/articles/dataset/Kaggle_Display_Advertising_Challenge_dataset/5732310

太棒了！这里可以下载！

**Comment by liquor233** [comment]
这个下载的格式是不是不太对呀

**Comment by zanshuxun** [comment]
> 这个下载的格式是不是不太对呀

愿闻其详

**Comment by YibinXie** [comment]
@zanshuxun 
https://www.kaggle.com/mrkmakr/criteo-dataset
There is also a duplicate version here. Higher download speed for Chinese users.

**Comment by ningyuwhut** [comment]
https://ailab.criteo.com/ressources/
