### ISSUE TITLE
SparseFeat 的用法

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#312]
您好：

我们的数据集一般分为 训练集 验证集 和测试集  
sparse_feature_columns = [SparseFeat(feat, vocabulary_size=data[feat].nunique(),embedding_dim=4)
                           for i,feat in enumerate(sparse_features)]
想问如果这三种数据集分别使用SparseFeat，得到的embedding 会不同吧，比如三种集合数据的itemid列，虽然值都是1000， 但是由于nunique 不同（测试集只是其中一部分，所以会少），因为sparse_feature_columns  可能有问题，想知道有什么办法处理，这跟fit_transform 类似。

**Comment by whk6688** [comment]
特别是当要实时预测的时候  需要把1000 实时编码，希望告知 多谢

**Comment by zanshuxun** [comment]
1. 如果是离线实验的话：
一般是先对所有数据统一做fit_transform、调用SparseFeat、切分数据集吧 就像例子中的这样：
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/examples/run_classification_criteo.py#L22
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/examples/run_classification_criteo.py#L28
https://github.com/shenweichen/DeepCTR/blob/e9c8f08f861293d5dc2f4e005b7b6ed47125ef17/examples/run_classification_criteo.py#L39
为什么要【三种数据集分别使用SparseFeat】呢
2. 线上预测的话 也就是itemid事先未知
一般是对id做hash吧 例子中也有
