### ISSUE TITLE
特征统一编码

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#313]
deepfm中各个特征应该是统一编码的，从而学到两两特征之间的关系，但是在我们的例子中，各个特征是独立编码的，有点不明白
for feat in sparse_features:
    lbe = LabelEncoder()
    data[feat] = lbe.fit_transform(data[feat])

望解答。

**Comment by zanshuxun** [comment]
> deepfm中各个特征应该是统一编码的，从而学到两两特征之间的关系

这句话有什么依据吗

**Comment by whk6688** [comment]
在https://cloud.tencent.com/developer/article/1450677 （对应的项目是https://github.com/ChenglongChen/tensorflow-DeepFM）这篇文章中，好像是统一编码的。 我也用过这个项目，效果也不错，所以有点疑惑。

另外如果在deepctr中用统一编码  auc 只有0.5*

**Comment by zanshuxun** [comment]
这个项目确实是对所有特征统一编码的。

但是，对原始类别特征重新编码的方式应该是不影响特征交叉的，因为fm部分做特征交叉时使用的是embedding。
独立编码是每个特征有其独立的embedding_matrix，统一编码相当于所有特征都从一个大的embedding_matrix里取embedding。这两种实现方式都可以的。

效果的差异，会不会因为其他超参数不同或者数据划分不同？
