### ISSUE TITLE
请问deepfm训练的模型，在tfserving部署后，能不能提供grpc or https预测的demo？构造和训练数据一样的输入，传入tfserving一直报错

### ISSUE THREAD

**Issue by RONG-SONG** [shenweichen/DeepCTR#320]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Comment by lonngxiang** [comment]
你是保存的双眸格式呢模型
