### ISSUE TITLE
SparseFeat(feat, vocabulary_size=train_df[feat].nunique(),embedding_dim=32)  用java实时预测有bug

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#323]
比如某一列，有0,1,2 三个值（其中0不常见，7天的训练集没有0值），训练完毕后，  此时用java来预测含有值2的数据 （index[0][0]=2）， 报错。Exception in thread "main" java.lang.IllegalArgumentException: indices[0,0] = 2 is not in [0, 2).  python预测不报错。也就是说vocabulary_size=train_df[feat].nunique() 从0开始编码，将这一列编码成0,1两个值。 java来预测，越界了。不知道python是如何处理的，不报错。

**Comment by shenweichen** [comment]
可以不用`nunqiue()`，提前设置一个较大的范围，或者使用`use_hash=True`

**Comment by whk6688** [comment]
目前使用max()+1
