### ISSUE TITLE
tensorboard scalar只显示loss，没有显示其它的metrics

### ISSUE THREAD

**Issue by pengyuan** [shenweichen/DeepCTR#328]
**Describe the bug(问题描述)**
看deepctr.estimator.utils文件中, Head class中的eval_metric_ops含有LogLoss/AUC等metric，但是:
tensorboard scalar只显示loss，没有显示其它的metrics
![image](https://user-images.githubusercontent.com/2572263/108591887-ec86fe00-73a5-11eb-83c0-cc87de2300ed.png)

**To Reproduce(复现步骤)**
1. DeepFMEstimator
2. 本地开不同端口，伪分布式训练
3. MODEL_DIR下生成的events.out.tfevents.*文件内容如下:
/Users/eric/PycharmProjects/aaa/events.out.tfevents.1613811968.macbook.local
1 {'loss': 265.6201477050781}
4 {'loss': 118.00953674316406}
7 {'loss': 73.12511444091797}
10 {'loss': 67.50395202636719}
13 {'loss': 49.413909912109375}

**Operating environment(运行环境):**
python version is 3.6.5
tensorflow                     2.3.1
tensorflow-estimator           2.3.0
deepctr                        0.8.4

**Comment by pengyuan** [comment]
有人有遇到同样的问题吗？

**Comment by prcjsczllc** [comment]
同问

**Comment by zanshuxun** [comment]
> 本地开不同端口，伪分布式训练

单机运行有auc等指标吗？
