### ISSUE TITLE
有没有人会这个入门问题？多谢多谢多谢

### ISSUE THREAD

**Issue by guotong1988** [shenweichen/DeepCTR#329]
https://github.com/ChenglongChen/tensorflow-DeepFM/issues/57

**Comment by AmazingCreator** [comment]
deepfm训练用的是binary_cross_entropy_loss，那三张图比较的是gini分数，两者没有必然的相关性。

**Comment by guotong1988** [comment]
也就是 https://github.com/ChenglongChen/tensorflow-DeepFM 有点问题？

**Comment by zanshuxun** [comment]
> 也就是 https://github.com/ChenglongChen/tensorflow-DeepFM 有点问题？

用的指标不同 不能说是有问题
