### ISSUE TITLE
attention layer weights in DIN

### ISSUE THREAD

**Issue by minarastgar** [shenweichen/DeepCTR#330]
Hi, Could you please show me how to get the weights of SequencePoolingLayer to visualize attention? 
Given a test sample, I am interested in seeing what items (keys_emb_list) had the biggest impact on the target item (query_emb_list) @shenweichen

**Comment by minarastgar** [comment]
any idea how to solve this problem?

**Comment by shenweichen** [comment]
set `return_score=True` in `AttentionSequencePoolingLayer` can get the attention score of DIN

**Comment by chiahualee0321** [comment]
I am also interested in getting the attention layer weights. I have tried setting `return_score=True`. However, I am still not seeing anything returned by calling `model.get_layer('attention_sequence_pooling_layer').get_weights()`? Do you mind sharing some code snippets to extract attention weights? Thanks!
