### ISSUE TITLE
训练过慢

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#331]
作者您好，目前训练数据有点慢，一轮2000s，训练集数据量大概是5kw， 看gpu发现，GPU-Util 的值一直在跳动0->20%(一下0 一下20，然后又回到0)。使用的w&d，代码跟您提供的例子几乎一致， gpu ：Tesla V100。不知道问题在哪里，希望您能指点一下。多谢！

**Comment by AmazingCreator** [comment]
差不多的情况。我在GPU和CPU测试发现，速度相差不超过20%。感觉是dataset的IO跟不上训练的速度。

**Comment by JWenBin** [comment]
5kw一轮才2000s？啥模型？我跑的CPU版5KW基本内存爆掉，然后CPU利用率又低，看来得试试分布式训练

**Comment by guotong1988** [comment]
感觉不是 读数据这里的速度瓶颈，我试了从HDFS读和从本地读，GPU利用率差不多。

**Comment by guotong1988** [comment]
也许CPU训练就是目前最好的选择。

**Comment by liyuan97** [comment]
我也遇到了，GPU显存爆满。但是利用率很低。可能和下面这个warning有关

 UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
