### ISSUE TITLE
关于模型保存 加载 部署问题

### ISSUE THREAD

**Issue by lonngxiang** [shenweichen/DeepCTR#332]
麻烦咨询下，按照例子跑了下deepfm模型，那麻烦有模型保存 加载 部署相关案例吗

**Comment by zanshuxun** [comment]
保存 加载 文档里有
部署案例一般都是用在自己公司 没人会公开吧

**Comment by lonngxiang** [comment]
> 保存 加载 文档里有
> 部署案例一般都是用在自己公司 没人会公开吧

正常的部署流程比如tfserving应该还好吧

**Comment by lonngxiang** [comment]
> > 保存 加载 文档里有
> > 部署案例一般都是用在自己公司 没人会公开吧
> 
> 正常的部署流程比如tfserving应该还好吧

部署请参考：https://blog.csdn.net/weixin_42357472/article/details/113591311
