### ISSUE TITLE
why not set sparse as True

### ISSUE THREAD

**Issue by baituhuangyu** [shenweichen/DeepCTR#34]
why not set sparse as True this line 
`
sparse_input[feat.name] = Input(shape=(1,), name=prefix+'sparse_' + str(i) + '-' + feat.name)
`
tensorflow.python.keras.layers.Input
`
@tf_export('keras.layers.Input', 'keras.Input')
def Input(  # pylint: disable=invalid-name
    shape=None,
    batch_size=None,
    name=None,
    dtype=None,
    sparse=False,
    tensor=None,
    **kwargs):
`

**Comment by shenweichen** [comment]
@baituhuangyu 
In fact, in deepctr most of the input is non-zero, so the `sparse` argument is not set to True.

**Comment by baituhuangyu** [comment]
thanks!
