### ISSUE TITLE
keras 的batchnormal 参数训练过程中即使设置tranable=true ,但是预测时还是有问题的，你们的dice激活函数中使用了这个类，所以这个类是不是 也有问题

### ISSUE THREAD

**Issue by areafather** [shenweichen/DeepCTR#343]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Comment by zanshuxun** [comment]
> keras 的batchnormal 参数训练过程中即使设置tranable=true ,但是预测时还是有问题的

能具体说说有啥问题吗 我没搜到

**Comment by areafather** [comment]
是这样的，BN训练完moving_mean和moving_variance并没有保存，预测时候不是训练的那个值，导致再次加载模型预测不一致的情况，
