### ISSUE TITLE
Can not save the model with *tf* format because in the *DNN* layer modify the list

### ISSUE THREAD

**Issue by dengc367** [shenweichen/DeepCTR#344]
If we use the [*DNN*](https://github.com/shenweichen/DeepCTR/blob/a94a8ece8374339eda162df66db1324df56aaba1/deepctr/layers/core.py#L178) Layer, and want to save the model, the error ` *ValueError: Unable to save the object ListWrapper(...)* ` occurs like [Tensorflow Issue #36916](https://github.com/tensorflow/tensorflow/issues/36916).
It because the `Layer` list can not be used to update, only used to append.
Ref: [In order to support restoration on object creation, tracking is exclusively for append-only data structures](https://github.com/tensorflow/tensorflow/blob/c0b4a3a1fdbd619bd005067f6042ee24bcb59192/tensorflow/python/training/tracking/data_structures.py#L554)

**Comment by cbjs** [comment]
re

**Comment by cbjs** [comment]
```python
        self.activation_layers = [activation_layer(self.output_activation if i == len(self.hidden_units) - 1 and self.output_activation else self.activation)
                                  for i in range(len(self.hidden_units))]

```
