### ISSUE TITLE
请教一下为什么DCN最后有Linear的部分？原论文不是只有cross和deep的部分吗？

### ISSUE THREAD

**Issue by BenLucas7** [shenweichen/DeepCTR#347]
https://github.com/shenweichen/DeepCTR/blob/a94a8ece8374339eda162df66db1324df56aaba1/deepctr/models/dcn.py#L75

**Comment by liyuan97** [comment]
我也没想明白，但是效果还不错

**Comment by shenweichen** [comment]
这是一个扩展实现，用户实际使用时如果步输入linear特征列，那么就只有cross和deep部分，根据实际需要使用即可。
