### ISSUE TITLE
PNN非常慢而且占用大量内存

### ISSUE THREAD

**Issue by lyabc0826** [shenweichen/DeepCTR#35]
**Describe the question(问题描述)**
特征维度5000+，用的PNN模型且全部特征都是连续特征，在PNN初始化的时候非常慢，而且占用了大量的内存，大约不到30G，然后fit的时候，样本大约在20万+，60G内存都报内存错误了，请问下，这是我哪里使用错了吗？
另外我也测试了其他的样本集，特征在1500维左右，也都是连续特征，样本数在6万+，就一切运行是正常的

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - deepctr version [e.g. 0.2.3,]

**Comment by shenweichen** [comment]
@lyabc0826 可以提供下您使用PNN时初始化模型时使用的参数吗

**Comment by lyabc0826** [comment]
![image](https://user-images.githubusercontent.com/11676611/53564929-17f9f800-3b93-11e9-8631-45936cbc951c.png)

**Comment by shenweichen** [comment]
@lyabc0826  建议调低`embedding_size`这个参数试试(1,2,4)，另外为什么全部是连续特征呢？PNN其实并不是很适合处理大量连续特征，换言之，大量连续特征可以尝试使用普通的全连接神经网络。

**Comment by lyabc0826** [comment]
谢谢。之所以全部是连续特征，是因为我们之前用xgboost，离散特征都是已经one-hot过了，为了在处理特征的时候简单，因此全部按照连续特征放进模型PNN里。再请问下，我们这种情况怎么处理比较好？用哪个模型比较适合？

**Comment by shenweichen** [comment]
@lyabc0826 deepctr的输入要求是直接将离散特征进行label encode 或者hash encode之后作为离散特征输入输入即可，对于本身就是连续型的特征可以作为连续特征使用。
建议您参考样例的处理方式对特征进行简单的预处理~
