### ISSUE TITLE
使用DeepFMEstimator，怎么打印训练过程每轮的loss和auc情况

### ISSUE THREAD

**Issue by 1980695671** [shenweichen/DeepCTR#355]
二分类问题，模型用的是deepfm，DeepFMEstimator()函数，训练的时候怎么打印loss，加了hook也不行，什么都不打印，默默写模型文件
![image](https://user-images.githubusercontent.com/12100521/117533452-819da880-b01f-11eb-8dc0-46651eec3c36.png)

**Comment by zanshuxun** [comment]
在`model.train`之前加上一行`tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)`试试

**Comment by 1980695671** [comment]
可以啦，感谢感谢
