### ISSUE TITLE
训练一段时间后，会被kill掉，模型是DCN模型

### ISSUE THREAD

**Issue by WujiangXu** [shenweichen/DeepCTR#358]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
可以正常训练，但是训练几个batch之后，会被kill掉。由于数据量较大，使用的batch读入数据。
训练和推理的api使用的是train_on_batch 和 predict_on_batch

**Additional context**

**Operating environment(运行环境):**
 - python version 3
 - tensorflow version 1.9.0
 - deepctr version 0.8.5

**Comment by cupcakefromchina** [comment]
> 可能是train_on_batch和predict_on_batch的问题？你用一部分数据，用train和predict试试看会不会每个epoch都增高

经测试，用一部分数据的话，在前面几个epoch，train和predict时，内存也会上升，但是后面epoch就会稳定住。但是如果用train_on_batch 或 predict_on_batch 就会内存一直上升。
请问train和predict能取代train_on_batch/predict_on_batch吗，有没有什么简单的解决方案。

**Comment by zanshuxun** [comment]
您好，针对无法一次性全部读入内存的数据，可以使用`fit_generator`方法替代`fit`方法。
具体用法请参考
https://deepctr-doc.readthedocs.io/en/latest/Model_Methods.html#fit-generator

**Comment by WujiangXu** [comment]
> 您好，针对无法一次性全部读入内存的数据，可以使用`fit_generator`方法替代`fit`方法。
> 具体用法请参考
> https://deepctr-doc.readthedocs.io/en/latest/Model_Methods.html#fit-generator

在这种情况下，有什么好的方法可以解决 数据预处理吗，因为读入的数据本身就是个batch的格式，在如何产生generator有点困惑，看上去generator的tuple数据是处理完的标签和输入。

**Comment by WujiangXu** [comment]
> > 您好，针对无法一次性全部读入内存的数据，可以使用`fit_generator`方法替代`fit`方法。
> > 具体用法请参考
> > https://deepctr-doc.readthedocs.io/en/latest/Model_Methods.html#fit-generator
> 
> 在这种情况下，有什么好的方法可以解决 数据预处理吗，因为读入的数据本身就是个batch的格式，在如何产生generator有点困惑，看上去generator的tuple数据是处理完的标签和输入。

补充的是，不太可能把读入的数据存在本地，因为太大了。

**Comment by WujiangXu** [comment]
> 您好，针对无法一次性全部读入内存的数据，可以使用`fit_generator`方法替代`fit`方法。
> 具体用法请参考
> https://deepctr-doc.readthedocs.io/en/latest/Model_Methods.html#fit-generator

是不是我用batch_data+处理数据的函数就等于一个generator呢？
