### ISSUE TITLE
DIN model misses parameters 'training' when calling the DICE activation function  DIN模型在调用DICE时缺少参数training

### ISSUE THREAD

**Issue by wc591723150** [shenweichen/DeepCTR#360]
**Describe the bug(问题描述)**

DIN model misses parameters 'training' when calling the DICE activation function  
DIN模型在调用DICE时缺少参数training

DeepCTR/deepctr/layers/core.py/ line193  
fc = self.activation_layers [i] (fc)
这导致DICE的BN无法开启训练模式，参数被冻结

**Additional context**
但是，如果传入training(  fc = self.activation_layers[i](fc，training = training)  )，会导致其他激活函数不可用，关联到DeepCTR/deepctr/layers/activation.py/ line66

**Comment by shenweichen** [comment]
在下个版本(v0.8.7)会先通过异常处理的方式加入对training参数的处理，后续再考虑更优雅的实现方式。
