### ISSUE TITLE
Fail to save model with Transformer layers with use_positional_encoding=True.

### ISSUE THREAD

**Issue by workingloong** [shenweichen/DeepCTR#365]
**Describe the bug(问题描述)**

**To Reproduce(复现步骤)**
```
from deepctr.model.bst import BST
model = BST()
tf.saved_model.save(model)
```
![image](https://user-images.githubusercontent.com/18071380/118910880-d6aeb800-b957-11eb-994c-5c20c3bdbb8a.png)

**Operating environment(运行环境):**
 - python version 3.6
 - tensorflow version 2.1.2
 - deepctr version 0.8.3

**Additional context**

We cannot create a variable in the `call` function 
https://github.com/shenweichen/DeepCTR/blob/a94a8ece8374339eda162df66db1324df56aaba1/deepctr/layers/sequence.py#L523-L525

We should create variables in the build function and then call them in the `call` function

**Comment by shenweichen** [comment]
this will be fixed in the next release version(v0.8.7)
