### ISSUE TITLE
为什么train_model_input 的shape是 (feature_num, data_num) 而不是 (data_num, feature_num)?

### ISSUE THREAD

**Issue by razrLeLe** [shenweichen/DeepCTR#37]
这里的train_model_input 是run_classification_criteo.py 中的模型输入数据。

**Comment by shenweichen** [comment]
这个是因为内部实现的时候对于每一个field的输入对应了一个Input(),而不是使用一个Input()包括所有的输入。
所以输入其实是若干个Input，每个Input的维度是(1,data_num)，拼接在一起就是你看到的(field_num,data_num)

**Comment by razrLeLe** [comment]
@shenweichen 十分感谢能够这么迅速回复！

我还想请教一下关于「内部实现的时候对于每一个field的输入对应了一个Input()，而不是使用一个Input()包括所有的输入。」这样输入数据是出于什么方面的考虑吗？

**Comment by shenweichen** [comment]
这个实现方式属于历史遗留下来的，刚开始写第一个版本的时候就是这样写的，当时想的是用name:Input这样的字典可以方便的根据特征拿到输入，然后去取对应的embedding向量，如果只用一个input需要另外存一个特征名到input索引的映射，当然这个实现也不麻烦。

**Comment by razrLeLe** [comment]
了解了，多谢🙏～
