### ISSUE TITLE
feature_column 支持embedding向量特征输入吗？

### ISSUE THREAD

**Issue by lonngxiang** [shenweichen/DeepCTR#372]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.5.0, 2.4.0]
 - deepctr version [e.g. 0.8.3,]

**Comment by zanshuxun** [comment]
https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-add-a-long-dense-feature-vector-as-a-input-to-the-model

**Comment by lonngxiang** [comment]
> https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-add-a-long-dense-feature-vector-as-a-input-to-the-model

多谢，麻烦问下item_id = np.array([[30],[20],[10]]) ，30,20就是表示获取30,20位的embedding吗；然后fixlen_feature_names是什么呢，我看后续没有使用？

**Comment by duankai** [comment]
nice

**Comment by dzzxjl** [comment]
> > https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-add-a-long-dense-feature-vector-as-a-input-to-the-model
> 
> 多谢，麻烦问下item_id = np.array([[30],[20],[10]]) ，30,20就是表示获取30,20位的embedding吗；然后fixlen_feature_names是什么呢，我看后续没有使用？

这里的[30]和[20]，都是原始的item id
