### ISSUE TITLE
训练集不平衡的问题

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#381]
作者您好：
       我的数据集正负样本不平衡，几乎为1:6，负样本较大，我是否需要进行如下设置：

class_weights={0:1.,1:6.}
history = model.fit(train_model_input, train_df[target].values,
                    batch_size=30000, epochs=26, verbose=2, validation_split=0.2,callbacks=[es],class_weight=class_weights)

即增加class_weights。

感激

**Comment by zanshuxun** [comment]
实验验证一下
