### ISSUE TITLE
Estimator 如何保存模型，没有找到对应的例子

### ISSUE THREAD

**Issue by whk6688** [shenweichen/DeepCTR#386]
model = WDLEstimator(linear_feature_columns, dnn_feature_columns, task='binary',
                     config=tf.estimator.RunConfig(tf_random_seed=2021,log_step_count_steps=1,keep_checkpoint_every_n_hours=1),
                     dnn_optimizer="Adam")

early_stopping = tf.estimator.experimental.stop_if_no_increase_hook(model,metric_name='auc',max_steps_without_increase=3)
model.train(train_model_input, hooks=[early_stopping])
#保存模型，不知道怎么实现

谢谢

**Comment by zanshuxun** [comment]
看一下estimator的文档

https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator

**Comment by dengc367** [comment]
Estimator官方都不建议在新代码中使用了，建议用keras更好些。
