### ISSUE TITLE
run_multivalue_movielens_hash.py中对string类型的变长序列pad_sequences，padding后的结果无法理解

### ISSUE THREAD

**Issue by rogerxsj** [shenweichen/DeepCTR#389]
![image](https://user-images.githubusercontent.com/6982669/125080546-82be8500-e0f7-11eb-9bae-1b4f787db70b.png)
![image](https://user-images.githubusercontent.com/6982669/125080638-a1bd1700-e0f7-11eb-9306-a4c5962db3dc.png)

padding之后原string特征值被截断，请问是否有问题？
@shenweichen

**Comment by JiaweiCui** [comment]
genres_list = pad_sequences(genres_list, maxlen=max_len, padding='post', dtype=object, value=0).astype('str')
这样就好了
