### ISSUE TITLE
How to perform regularization on CIN layer?

### ISSUE THREAD

**Issue by jinj200200** [shenweichen/DeepCTR#39]
**Describe the question(问题描述)**
How to perform regularization on CIN layer.Seems that's no regularizer parameter in the function CIN in the deepctr.layers.interaction.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepctr version [e.g. 0.2.3,]

**Comment by shenweichen** [comment]
@jinj200200  I will add the reg parameter in CIN in next version.

now you can modify the source code of CIN in deepctr.layers.interaction
in line 299
```python

            self.filters.append(self.add_weight(name='filter' + str(i),
                                                shape=[1, self.field_nums[-1]* self.field_nums[0], size],
                                                dtype=tf.float32, 
                                                 initializer=glorot_uniform(seed=self.seed + i), 
                                                regularizer=l2(l2_reg_w)))
```

**Comment by jinj200200** [comment]
> @jinj200200 I will add the reg parameter in CIN in next version.
> 
> now you can modify the source code of CIN in deepctr.layers.interaction
> in line 299
> 
> ```python
>             self.filters.append(self.add_weight(name='filter' + str(i),
>                                                 shape=[1, self.field_nums[-1]* self.field_nums[0], size],
>                                                 dtype=tf.float32, 
>                                                  initializer=glorot_uniform(seed=self.seed + i), 
>                                                 regularizer=l2(l2_reg_w)))
> ```

Thank,that helps a lot.
