### ISSUE TITLE
RuntimeError: Unable to create link (name already exists

### ISSUE THREAD

**Issue by eshaoliu** [shenweichen/DeepCTR#397]
**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.
tf2.3 包含自定义层保存模型的时候报RuntimeError: Unable to create link (name already exists)
方法用的是from tensorflow.python.keras.models import  save_model的save_model
1.4版本没有这个问题
**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [3.6]
 - tensorflow version [e.g. 2.3]
 - deepctr version [e.g. 0.8.5,]

**Additional context**

**Comment by dengc367** [comment]
具体是哪个模型，最好截个图。

**Comment by zanshuxun** [comment]
请按照bug report模板给出复现步骤
