### ISSUE TITLE
How to run the demo with GPU

### ISSUE THREAD

**Issue by Cong-Zou** [shenweichen/DeepCTR#40]
**Describe the question(问题描述)**
Im testing the deepctr demo. However, it's running with CPU. How can I modify the code to run it with my own GPU?
Thanks for ur answering.

**Additional context**

**Operating environment(运行环境):**
 - python version [3.6]
 - tensorflow version [1.6.0]
 - tensorflow-gpu version [1.6.0]
 - deepctr version [0.3.1]

**Comment by shenweichen** [comment]
@Cong-Zou Hi,if you have installed `tensorflow-gpu`,it will run with GPU automatically

**Comment by Cong-Zou** [comment]
Thank you for the reply..
The fact is that I have installed tensorflow-gpu 1.6.0..
But it still runs with CPU..

**Comment by shenweichen** [comment]
@Cong-Zou check 
first check if  you have instelled `deepctr` and `tensorflow-gpu` in the same evironment.
then, run the following code and make sure thers is at least one **GPU** device in the output of the code.
```python
import os
from tensorflow.python.client import device_lib
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "99"
 
if __name__ == "__main__":
    print(device_lib.list_local_devices())
```

**Comment by Cong-Zou** [comment]
They are in the same environment for sure.
Thanks a lot！
I will test the code tomorrow morning and tell you the result then..

**Comment by Cong-Zou** [comment]
I have solved it. Thank you!
I uninstalled the tensorflow-gpu-1.6.0 and deepctr and then I installed them again. Now it finally works.
The reason might be that my tensorflow-gpu has some package dependency problems..
