### ISSUE TITLE
FM的实现疑问

### ISSUE THREAD

**Issue by xuanzebi** [shenweichen/DeepCTR#405]
FM的原始论文中 最后化简为如下，会有vi的参数，但是代码中具体实现我看直接对变量进行操作了。似乎没有了这部分参数。
![image](https://user-images.githubusercontent.com/26642184/132087104-0913e3ab-7d60-422f-b149-9ad00894c4fc.png)

![image](https://user-images.githubusercontent.com/26642184/132087138-755d7f62-1177-4edb-89ec-b288dc54921c.png)

顺便问下，这种实现的话，还支持每个类别的变量维度不同吗。感觉必须所有类别变量的维度设为一致。
不知道哪里理解错了吗~

**Comment by zanshuxun** [comment]
1、https://github.com/shenweichen/DeepCTR/issues/171
2、有哪种实现支持每个类别embedding维度不同吗？论文公式里的n岂不是就要求了所有类别embedding维度都必须是n

**Comment by xuanzebi** [comment]
To 2 FM确实是，最近刚好看了FmFM论文，支持类别维度不同。

**Comment by guotong1988** [comment]
小白问下原始论文的出处？多谢！@xuanzebi
