### ISSUE TITLE
load model 报错

### ISSUE THREAD

**Issue by heshanshanhg3** [shenweichen/DeepCTR#41]
使用deepctr 包 DCN 训练模型没有报错。save模型：   save_model(model,outfile_model2) #outfile_model2="./model/DCN.h5"
   没有报错，但是load model：
model = load_model(outfile_model2, custom_objects)
报错：TypeError: issubclass() arg 1 must be a class
![image](https://user-images.githubusercontent.com/7931706/54418696-8dbaa380-46fd-11e9-86a1-10e0dba6eb7b.png)

 @shenweichen 麻烦帮忙看看问题在哪里怎么解决？我调用包的其他算法也是同样错误

**Comment by shenweichen** [comment]
@heshanshanhg3 您好，建议先切换到python3,建议python3.6，然后安装最新版本得deecptr(v0.3.1)，看看有没有这个问题~

**Comment by heshanshanhg3** [comment]
@shenweichen  更换了版本，问题解决

**Comment by huminwudi** [comment]
你好，我想问一下 这个custom_objects是怎么自定义的！我也出现了这问题

**Comment by shenweichen** [comment]
@huminwudi please refer to this #107
