### ISSUE TITLE
sparse_feature中embeddings_initializer维度如何设置？

### ISSUE THREAD

**Issue by fxxxxxxz** [shenweichen/DeepCTR#412]
假如我有10000个userid，分别为1~10000连续编码，希望将其嵌入到10维空间中。那么
SparseFeat(name, vocabulary_size, embedding_dim, use_hash, vocabulary_path, dtype, embeddings_initializer, embedding_name, group_name, trainable)
中的vocabulary_size应该设置为10001（0留作缺失值）。请问此时的embeddings_initializer矩阵维度应该为10000 * 8还是10001 * 8呢？
如果为10001 * 8的话，是否应该在embeddings_initializer矩阵第一行填充任意向量呢？

**Comment by zanshuxun** [comment]
> 请问此时的embeddings_initializer矩阵维度应该为10000 * 8还是10001 * 8呢？

这个问题相信你试一下跑一下就知道答案了

> 如果为10001 * 8的话，是否应该在embeddings_initializer矩阵第一行填充任意向量呢？

这个要看后面如何使用这个填充值，如果用作序列特征而且使用padding and mask，那embedding数值无所谓

**Comment by fxxxxxxz** [comment]
> > 请问此时的embeddings_initializer矩阵维度应该为10000 * 8还是10001 * 8呢？
> 
> 这个问题相信你试一下跑一下就知道答案了
> 
> > 如果为10001 * 8的话，是否应该在embeddings_initializer矩阵第一行填充任意向量呢？
> 
> 这个要看后面如何使用这个填充值，如果用作序列特征而且使用padding and mask，那embedding数值无所谓

非常感谢你的回复，这个问题经实验已解决。

在实验的过程中，我发现官方文档**FAQ部分有一个小问题**。
https://deepctr-doc.readthedocs.io/en/latest/FAQ.html#how-to-use-pretrained-weights-to-initialize-embedding-weights-and-frozen-embedding-weights中表示使用tf.initializers.identity()来作为初始化器，在tf1.12版本中这种设置无法正常工作，**初始化后的embedding矩阵为全零矩阵**。而使用tf.initializers.Constant()可以正常工作。
