### ISSUE TITLE
How does DeepFM handle values of a feature not seen in training set?

### ISSUE THREAD

**Issue by joelpv25** [shenweichen/DeepCTR#415]
One of the features in my trained DeepFM model is user_id. If there's a new user during inference how does DeepFM handle it? Thank you!

**Comment by zanshuxun** [comment]
You can use hash for unseen user_id:
https://github.com/shenweichen/DeepCTR/blob/master/examples/run_classification_criteo_hash.py

**Comment by Cyborg-vs-Droids** [comment]
After going through a lot of sources, I found this amazing source-
https://github.com/gcampanella/pydata-london-2019/blob/master/pydata_london_2019.pdf
