### ISSUE TITLE
How to share embeddings among features?

### ISSUE THREAD

**Issue by joelpv25** [shenweichen/DeepCTR#418]
I have a dataset where I have 3 columns, created_user, delegated_user, tagged_user which are different users but come from the same population of users. How do I share embeddings among them? I was thinking of using multi-value input like this example - https://deepctr-doc.readthedocs.io/en/latest/Examples.html#multi-value-input-movielens but the order matters in this case. Do I create separate embeddings? Is there a way to share embeddings?

**Comment by haiming2019** [comment]
set the same embedding_name

**Comment by joelpv25** [comment]
Thank you! What's the difference between name, embedding_name, and group_name?

**Comment by shenweichen** [comment]
for example , we have 3 feature group named A B C，if we want to share embedding of feature group A and B wen can set a a same `embedding_name` for A and B。
`group_name` only works in `DeepFM` and `FLEN`, the model will do feature interactions for feature groups  having same `group_name`
