### ISSUE TITLE
How to add a long feature vector as a feature to the model?

### ISSUE THREAD

**Issue by Cong-Zou** [shenweichen/DeepCTR#42]
**Describe the question(问题描述)**
Hello Weichen!
I have a question like this.
For example, now I have extracted visual feature vectors with the dimension of 2048 of every item. I need to embed it to your CTR model (like in the docs demo). Thus, how can I use them in the sparse or dense features to train the model and make predictions?
Thanks a lot! 

**Additional context**

**Operating environment(运行环境):**
 - python version [3.6]
 - tensorflow version [1.6.0]
 - deepctr version [e.g. 0.3.1]

**Comment by shenweichen** [comment]
@Cong-Zou  please refer to 

https://github.com/shenweichen/Bytedance_ICME2019_challenge_baseline/blob/master/model.py
![image](https://user-images.githubusercontent.com/18311786/54490254-37ad5200-48ef-11e9-9f90-ceb70a665322.png)


line 20,21 define  a input for continue 128-dimension feature

you can perform the desired operation on `video_input` tensor

when fit the model,the input to the model is `[original input list] + [video_input_array]`

**Comment by Cong-Zou** [comment]
I have read about the code..
But sorry, I'm a little confused about it.
After I add the two sentences (delete the annotations) in model.py as u suggest,
in train.py, as shown below:
![image](https://user-images.githubusercontent.com/28620426/54491955-7b0ebd00-48fd-11e9-9f9c-026026d3841c.png)
do I just need to extend the train and test model input lists with the video feature arrays?

**Comment by shenweichen** [comment]
yes~

**Comment by Cong-Zou** [comment]
Hi Weichen,
I have tried like this..
![image](https://user-images.githubusercontent.com/28620426/54511758-e3f14600-498c-11e9-8207-ad5dc91f0b5a.png)
The train['video_feature'].values is a ndarray(D=#records) and every entry in it is also an array(D=128).
However, I run the code and get the error as shown below:
![image](https://user-images.githubusercontent.com/28620426/54511900-637f1500-498d-11e9-9c43-8bd0badd6004.png)
May I ask the reason about it?
Thanks a lot!

**Comment by shenweichen** [comment]
@Cong-Zou  print the shape of `train['video_feature'].values` and `test['video_feature'].values`,make sure their shape are`(#records,128)` .

**Comment by Cong-Zou** [comment]
Great! It works now..
Thank you again!
