### ISSUE TITLE
Support for TensorFlow 1.13

### ISSUE THREAD

**Issue by diogoff** [shenweichen/DeepCTR#43]
DeepCTR requires tensorflow <= 1.12. The problem is that tensorflow-gpu 1.12 (via pip) has been compiled with CUDA 9. This means that we cannot upgrade to CUDA 10 (unless we compile tensorflow 1.12 from sources, which makes little sense since it has superseded by a newer version).

Is it possible to upgrade DeepCTR to support tensorflow 1.13? This way we could pip install tensorflow-gpu 1.13, which has been compiled with CUDA 10, so we could upgrade from CUDA 9 to CUDA 10. Thanks.

**Comment by shenweichen** [comment]
@diogoff Sorry for this, there are some compatibility issues to be solved in tf1.13, and may be I will directly adapted it to tf.2.0 later+

**Comment by shenweichen** [comment]
@diogoff  hi, deepctr has supported tf 1.13,1.14 and 2.0 since v0.6.0
