### ISSUE TITLE
tf2.7版本 报错

### ISSUE THREAD

**Issue by moseshu** [shenweichen/DeepCTR#432]
WARNING:tensorflow:
The following Variables were used a Lambda layer's call (tf.linalg.matmul_1), but
are not present in its tracked objects:
  <tf.Variable 'dense_1/kernel:0' shape=(64, 1) dtype=float32>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-62748b8da087> in <module>()
     31 
     32     # 4.Define Model,train,predict and evaluate
---> 33     model = DeepFM(linear_feature_columns, dnn_feature_columns, task='regression')
     34     model.compile("adam", "mse", metrics=['mse'], )
     35 

4 frames
/usr/local/lib/python3.7/dist-packages/keras/engine/functional_utils.py in is_input_keras_tensor(tensor)
     46   if not node_module.is_keras_tensor(tensor):
     47     raise ValueError(_KERAS_TENSOR_TYPE_CHECK_ERROR_MSG.format(tensor))
---> 48   return tensor.node.is_input
     49 
     50 

AttributeError: 'KerasTensor' object has no attribute 'node'
是不是tensorflow版本的问题？

**Comment by 1360011612** [comment]
你解决这个问题了吗

**Comment by jasonhuxinlei** [comment]
一样的错误，同问这个问题，我改成了tf2.2还是报错

**Comment by 15pengyi** [comment]
是一致性的问题，解法是：1）所有 tf.keras.xxx.yyy 都改成 yyy；2）文件头增加 from tensorflow.python.keras.xxx import yyy。

**Comment by 15pengyi** [comment]
> tf.keras

原因是 tf.keras 会引用独立的 keras 包；而与 tensorflow.python.keras 产生冲突。具体而言，keras 的 input 会生成并使用 node 属性；而 tensorflow.python.keras 里的并不需要。通过 debug 可以发现这个问题，正在考虑提 pull request。

**Comment by XuJing1022** [comment]
M1 tf2.7遇到相同问题，期待解决

**Comment by LiuYang-0410** [comment]
有能快速解决/或者暂时解决的方法么？

**Comment by LiuYang-0410** [comment]
> 有能快速解决/或者暂时解决的方法么？

tensorflow 1.15 可以

**Comment by fengyinyang** [comment]
> 是一致性的问题，解法是：1）所有 tf.keras.xxx.yyy 都改成 yyy；2）文件头增加 from tensorflow.python.keras.xxx import yyy。
可不可以把tf.python.keras改成tf.keras呢？
我现在把按你说的都改了，模型训练都没有问题，现在的问题是没法直接用load_model，比如我用了tf.keras.metrics.AUC()，在加载训练好的模型的时候，会出现“AttributeError: 'AUC' object has no attribute '_serialized_attributes'”的错误，但是直接读取weights就可以

**Comment by StarryCatte** [comment]
> > tf.keras
> 
> 原因是 tf.keras 会引用独立的 keras 包；而与 tensorflow.python.keras 产生冲突。具体而言，keras 的 input 会生成并使用 node 属性；而 tensorflow.python.keras 里的并不需要。通过 debug 可以发现这个问题，正在考虑提 pull request。

小白提问：如果只是调用DeepFM，没有自定义layer，应该怎么修改呢？

**Comment by zhiqiang00** [comment]
> > > tf.keras
> > 
> > 
> > 原因是 tf.keras 会引用独立的 keras 包；而与 tensorflow.python.keras 产生冲突。具体而言，keras 的 input 会生成并使用 node 属性；而 tensorflow.python.keras 里的并不需要。通过 debug 可以发现这个问题，正在考虑提 pull request。
> 
> 小白提问：如果只是调用DeepFM，没有自定义layer，应该怎么修改呢？
 同样的问题，也是想用一个库，吧报错，请问解决了吗？

**Comment by 545487677** [comment]
我是这样解决的: 当我在调用deepfm的方法中，会出现以上问题。但是当我将deepfm中个别几行代码进行修改即可运行

dnn_logit = tf.keras.layers.Dense(
        1, use_bias=False, activation=None)(dnn_output)
改为
dnn_logit = Dense(
        1, use_bias=False, activation=None)(dnn_output)

以及
model = tf.keras.models.Model(inputs=inputs_list, outputs=output)
改为
model = Model(inputs=inputs_list, outputs=output)

还需要写入
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.models import Model

即可运行

**Comment by insect1111** [comment]
> 

牛的

**Comment by VinnyHu** [comment]
> > tf.keras
> 
> 原因是 tf.keras 会引用独立的 keras 包；而与 tensorflow.python.keras 产生冲突。具体而言，keras 的 input 会生成并使用 node 属性；而 tensorflow.python.keras 里的并不需要。通过 debug 可以发现这个问题，正在考虑提 pull request。

你好，首先向您请教下，tensorflow.python.keras与tf.keras有什么区别嘛？

还有就是我搜了下，好像说tensorflow.python.keras是私有，开发tf用的，不推荐用户使用，一律推荐直接用tf.keras

**Comment by moseshu** [comment]
> 你解决这个问题了吗

没有解决，我换成torch了，要么再用tf2.7版本再写一个，tf版本太恶心了

**Comment by shenweichen** [comment]
we have solved this problem in deepctr v0.9.1,please use `pip install -U deepctr` to upgrade latest version.

**Comment by liuyang-aml** [comment]
> 我现在把按你说的都改了，模型训练都没有问题，现在的问题是没法直接用load_model，比如我用了tf.keras.metrics.AUC()，在加载训练好的模型的时候，会出现“AttributeError: 'AUC' object has no attribute '_serialized_attributes'”的错误

请问这个问题如何解决的？

**Comment by AltmanHao** [comment]
> > 我现在把按你说的都改了，模型训练都没有问题，现在的问题是没法直接用load_model，比如我用了tf.keras.metrics.AUC()，在加载训练好的模型的时候，会出现“AttributeError: 'AUC' object has no attribute '_serialized_attributes'”的错误
> 
> 请问这个问题如何解决的？

请问你解决了？我也遇到这个问题
