### ISSUE TITLE
deepfm network structure difference

### ISSUE THREAD

**Issue by Pengtai9928** [shenweichen/DeepCTR#434]
I noticed that for deemFM model, [the implemented hidden layer dimensions are 256-128-64](https://github.com/shenweichen/DeepCTR/blob/cd9643c2dc2a25c8b27269e2033b1a0b6aafcac7/deepctr/models/deepfm.py#L21). However in the original deepFM paper, the network structure specified is 400-400-400 (screenshot below). May I ask why is the network structure different? 

![image](https://user-images.githubusercontent.com/44203544/145175119-9b102ce1-e75e-42f1-a33a-bc0bf3122df2.png)

**Comment by shenweichen** [comment]
it is just an example ,you can set this parameter to 400-400-400 by yourself

**Comment by Pengtai9928** [comment]
okay, thank you!
