### ISSUE TITLE
run_dien.py test reports "localhost/dnn/bias0/N10tensorflow3VarE does not exist"

### ISSUE THREAD

**Issue by mingxiaoh** [shenweichen/DeepCTR#458]
1. NV A100 is used, try test on docker nvcr.io/nvidia/tensorflow:21.10-tf2-py3( or you can just install tensorflow==2.8.0)
3. install DeepCTR
4. cd DeepCTR/examples && python run_dien.py
Log see below:
  File "run_dien.py", line 57, in <module>
    model = DIEN(feature_columns, behavior_feature_list,
  File "/usr/local/lib/python3.8/dist-packages/deepctr-0.9.0-py3.8.egg/deepctr/models/sequence/dien.py", line 194, in DIEN
  File "/usr/local/lib/python3.8/dist-packages/deepctr-0.9.0-py3.8.egg/deepctr/models/sequence/dien.py", line 76, in interest_evolution
  File "/usr/local/lib/python3.8/dist-packages/deepctr-0.9.0-py3.8.egg/deepctr/models/sequence/dien.py", line 40, in auxiliary_loss
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 784, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.FailedPreconditionError: in user code:

    /usr/local/lib/python3.8/dist-packages/deepctr-0.9.0-py3.8.egg/deepctr/layers/core.py:190 call  *
        fc = self.activation_layers[i](fc, training=training)
    /usr/local/lib/python3.8/dist-packages/keras/engine/base_layer_v1.py:732 __call__  **
        base_layer_utils.create_keras_history(inputs)
    /usr/local/lib/python3.8/dist-packages/keras/engine/base_layer_utils.py:175 create_keras_history
        _, created_layers = _create_keras_history_helper(tensors, set(), [])
    /usr/local/lib/python3.8/dist-packages/keras/engine/base_layer_utils.py:251 _create_keras_history_helper
        constants[i] = backend.function([], op_input)([])
    /usr/local/lib/python3.8/dist-packages/keras/backend.py:4031 __call__
        fetched = self._callable_fn(*array_vals,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py:1478 __call__
        ret = tf_session.TF_SessionRunCallable(self._session._session,

    FailedPreconditionError: 2 root error(s) found.
      (0) Failed precondition: Could not find variable dnn/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/dnn/bias0/N10tensorflow3VarE does not exist.
         [[{{node dnn/BiasAdd/ReadVariableOp}}]]
         [[dnn/BiasAdd/ReadVariableOp/_9]]
      (1) Failed precondition: Could not find variable dnn/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/dnn/bias0/N10tensorflow3VarE does not exist.
         [[{{node dnn/BiasAdd/ReadVariableOp}}]]
    0 successful operations.
    0 derived errors ignored.

**Comment by mingxiaoh** [comment]
I can run it when remove python from *python.keras*

**Comment by HuipengXu** [comment]
same problem:
FailedPreconditionError: 2 root error(s) found.
      (0) FAILED_PRECONDITION: Could not find variable attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0/N10tensorflow3VarE does not exist.
         [[{{node attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp}}]]
         [[attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp/_9]]
      (1) FAILED_PRECONDITION: Could not find variable attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0/N10tensorflow3VarE does not exist.
         [[{{node attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp}}]]
    0 successful operations.
    0 derived errors ignored.

Where to modify python.keras? in DIEN.py?

**Comment by wandouqiang** [comment]
> same problem: FailedPreconditionError: 2 root error(s) found. (0) FAILED_PRECONDITION: Could not find variable attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0/N10tensorflow3VarE does not exist. [[{{node attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp}}]] [[attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp/_9]] (1) FAILED_PRECONDITION: Could not find variable attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/attention_sequence_pooling_layer/local_activation_unit/dnn_1/bias0/N10tensorflow3VarE does not exist. [[{{node attention_sequence_pooling_layer/local_activation_unit/dnn_1/BiasAdd/ReadVariableOp}}]] 0 successful operations. 0 derived errors ignored.
> 
> Where to modify python.keras? in DIEN.py?

change all tensorflow.python.keras to tensorflow.keras in deepctr, env tensorflow=2.13 python = 3.10
