### ISSUE TITLE
can't concat when embedding_size is set to "auto"

### ISSUE THREAD

**Issue by dev-wei** [shenweichen/DeepCTR#46]
**Describe the bug(问题描述)**
When set the embedding size to "auto", the Concatenate layer can't merge all input Embedding with different size at axis=2

def concat_fun(inputs, axis=-1):
    if len(inputs) == 1:
        return inputs[0]
    else:
        return Concatenate(axis=axis)(inputs) 

**To Reproduce(复现步骤)**
4. ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 1, 36), (None, 1, 30), (None, 1, 6), (None, 1, 12), (None, 1, 12), (None, 1, 30), (None, 1, 12)]

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepctr version [e.g. 0.2.3,]

**Additional context**

**Comment by shenweichen** [comment]
can you concat the emb list with `axis=-1`?

**Comment by dev-wei** [comment]
thanks for the quick response.

do you mean change "fm_input = concat_fun(deep_emb_list, axis=1)"
to "fm_input = concat_fun(deep_emb_list, axis=-1)"

?

**Comment by shenweichen** [comment]
the auto embedding mode is not supported when you use fm based model.

**Comment by dev-wei** [comment]
that sounds clear. Perhaps, we should add a validation error out there.

Also, I want to gain your opinion on "what is the right embedding size dataset has a number of sparse fields".

**Comment by shenweichen** [comment]
Thanks for your advice

Usually I search for a size in 4 8 12 16 32 64 etc

**Comment by dev-wei** [comment]
Thanks for the sharing. I will do extra tuning over there.

Currently, I am evaluate movie-len 100k with LR, the mse I got, based on epoch=10, embedding size=8 is not amazing. 

the train mse is 0.7317, and test mse is 0.9476 - for nfm model.

Do you have some metrics you could share?

I'd continue do more.

**Comment by dev-wei** [comment]
btw,  I love this repo and your quickness on responding. Good work.

**Comment by shenweichen** [comment]
Sorry I don’t have any  metrics on movie-len ~
