### ISSUE TITLE
sparsefeat densefeat 线上预测使用时需不需要处理这一步？

### ISSUE THREAD

**Issue by zaibian** [shenweichen/DeepCTR#468]
示例中没见到过上线部署的demo案例，看到训练时都需要运行sparsefeat densefeat等特征。请问如果我线上预测的话，特征还需要写同样的代码进行处理么？还是不用管这个特征处理？

**Comment by kristen1110** [comment]
比如离线和在线时都用这个特征处理方式，sparse_feature_columns = [SparseFeat(feat, vocabulary_size=self.df[feat].max()+1, embedding_dim=4) for i, feat in enumerate(self.sparse_feature)]，里面的参数不会变吗。例如，vocabulary_size不是随着数据集取值改变的吗？
