### ISSUE TITLE
How to Encode Numerical Sparse features?

### ISSUE THREAD

**Issue by leoanghelescu** [shenweichen/DeepCTR#47]
Question on encoding numerical sparse features:

How do we encode sparse features with non binary values? Say we have frequency/strength values in X for the sparse features (normalized between 0 and 1)? All my sparse features are already stored in separate columns. (col2 : col11133)

Currently I do this:
    sparse_features = ['col' + str(i) for i in range(2, n)]
    dense_features = []

    testing_dataframe[sparse_features] = testing_dataframe[sparse_features].fillna(0, )
    testing_dataframe[dense_features] = testing_dataframe[dense_features].fillna(0, )

    sparse_feature_list = [SingleFeat(feat, 0) for feat in sparse_features]
    dense_feature_list = [SingleFeat(feat, 0) for feat in dense_features]

    test_model_input = [df_test[feat.name].values for feat in sparse_feature_list] + \
                       [df_test[feat.name].values for feat in dense_feature_list]

This makes my network take much longer to initialize. I am using embedding of 50, with ~11K features.

I see the examples shown are more so categorical.

Any assistance would be greatly appreciated!

 - python version 3.6
 - tensorflow version 1.12.0
 - deepctr version latest

**Comment by shenweichen** [comment]
hi,please treat the  numerical sparse features as  dense features~

**Comment by leoanghelescu** [comment]
Thanks for your quick response. So basically we cannot reduce dimensionality for sparse numerical, right?

Reason I am asking is that my data is in FFM format (field:feature:value). The closest thing to this would be to just use categorical, correct?

Thanks
Leo

**Comment by XunGong99** [comment]
So, can model support coo or csr matrix type?

**Comment by shenweichen** [comment]
@leoanghelescu  for the format of (field:feature:value),
- #feature=1,#value >= 1,treat it as dense feature
- #feature>1,#value = 1,treat it as sparse feature
- #feature >1,#value > 1, now deepctr not support

**Comment by shenweichen** [comment]
@XunGong99  there is no need to use sparse matrix type in deepctr
