### ISSUE TITLE
相同环境运行xDeepFM报错，运行DeepFM是好的

### ISSUE THREAD

**Issue by ArtificialZeng** [shenweichen/DeepCTR#481]
WARNING:tensorflow:From E:\A_IDE\Anaconda3\envs\pp212\lib\site-packages\tensorflow_core\python\keras\initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "G:/rec_projects/deepfm_personalised/xdeepfm_train.py", line 53, in <module>
    model = xDeepFM(linear_feature_columns,dnn_feature_columns, task='binary')
  File "G:\rec_projects\deepfm_personalised\deepCTR\deepctr\models\xdeepfm.py", line 42, in xDeepFM
    linear_feature_columns + dnn_feature_columns)
  File "G:\rec_projects\deepfm_personalised\deepCTR\deepctr\feature_column.py", line 147, in build_input_features
    raise TypeError("Invalid feature column type,got", type(fc))
TypeError: ('Invalid feature column type,got', <class 'deepctr.feature_column.SparseFeat'>)

Process finished with exit code 1

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.Better with standalone code to reproduce the issue.

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [e.g. 3.6, 3.7]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.9.0,]

**Additional context**

**Comment by zanshuxun** [comment]
请给出复现步骤
