### ISSUE TITLE
关于 DCN 模型实现中，LR部分的疑问

### ISSUE THREAD

**Issue by LALBJ** [shenweichen/DeepCTR#488]
**Describe the question(问题描述)**
![image](https://user-images.githubusercontent.com/40877073/185033727-914cca9b-acdc-4220-aba9-de6459dc3444.png)
DCN 模型的源代码中如上图，在论文里的结构中好像并没有 LR 这个部分。
我想问一下，这里加这个的目的是什么呀？

**Comment by zanshuxun** [comment]
https://github.com/shenweichen/DeepCTR/issues/347
