### ISSUE TITLE
FM层维度问题

### ISSUE THREAD

**Issue by 2499088506** [shenweichen/DeepCTR#5]
代码中FM层做交叉后好像是1维。不应该是K（embedding的维度）吗？

**Comment by shenweichen** [comment]
请问您说的是哪份代码中哪一段？FM层是将原始embedding向量做两两内积，并求和，得到一个输出值。
![image](https://user-images.githubusercontent.com/18311786/44976778-cd5b4280-af98-11e8-9ec2-0959c2d3d69f.png)
