### ISSUE TITLE
DIN等模型为什么对目标物品和历史物品的embedding分别建立矩阵？与原论文实现不符

### ISSUE THREAD

**Issue by TangJiakai** [shenweichen/DeepCTR#507]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.10.0]
 - deepctr version [e.g. 0.9.2,]

**Comment by zanshuxun** [comment]
从哪里看出来目标物品和历史物品是分别建立embedding矩阵的？

**Comment by TangJiakai** [comment]
噢我明白了。DeepCTR是对于item和cate创建了两次Embedding，只不过后来的hist_xx_id覆盖了上一次由xx_id创建的Embedding。

**Comment by zanshuxun** [comment]
通过设置相同的embedding_name来使用共享embedding
