### ISSUE TITLE
如何保存deepctr-torch训练好的deepfm模型

### ISSUE THREAD

**Issue by RainFung** [shenweichen/DeepCTR#527]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
<img width="936" alt="image" src="https://github.com/shenweichen/DeepCTR/assets/23121539/49f1cfa6-fc23-458e-bb0f-d80866ee43a1">

**Comment by leixingzhi7** [comment]
you can save in the script "base_model.py" by using torch.save(model.state_dict(), './data/save_dict/deep_fm_epoch_{}.ckpt'.format(epoch)) at last in fit function

**Comment by RainFung** [comment]
thanks

LEI CHEN ***@***.***> 于2023年8月1日周二 13:11写道：
