### ISSUE TITLE
custom_object can't be imported

### ISSUE THREAD

**Issue by emremrah** [shenweichen/DeepCTR#53]
**Describe the bug(问题描述)**
`custom_objects` from `deepctr.utils` can't be imported. But `models`, `SingleFeat` etc. can be imported properly.

**To Reproduce(复现步骤)**
1. `pipenv shell` as I use pipenv
2. `python`
3. `from deepctr.utils import custom_objects`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'custom_objects'
```

**Operating environment(运行环境):**
 - python version `3.6`
 - tensorflow version `1.12.0`
 - deepctr version `0.3.2`

**Additional context**
Exact same code works well on my other PC.

Thanks for this great work.

**Comment by shenweichen** [comment]
Sorry for this mistake 
Try
from deepctr.layers import custom_objects

**Comment by emremrah** [comment]
Oh, no problem at all, thank you for the quick response and this work.

But why it worked with `deepctr.utils` on my other PC though?

**Comment by shenweichen** [comment]
Maybe it is an older version
