### ISSUE TITLE
Difference between embed_size = 1 and 'auto', all dense feature

### ISSUE THREAD

**Issue by leoanghelescu** [shenweichen/DeepCTR#54]
**Describe the question(问题描述)**

Hello, I would like to understand the difference between setting:

embed_size = 'auto'
vs.
setting embed_size = 1

ALL of my features all numerical and DENSE. Num features = 11190, binary

I have tried to print out tensor sizes and the model.summary() as follows:

```
    print('AUTO')
    model = DeepFM({"sparse": sparse_feature_list,
                    "dense": dense_feature_list}
                   , embedding_size='auto'
                   , use_fm=True
                   , hidden_size=(10,10)
                   , l2_reg_linear=0.0001
                   , l2_reg_embedding=0.00001
                   , l2_reg_deep=0.0001
                   , init_std=0.0001
                   , seed=1024
                   , keep_prob=0.8
                   , activation='relu'
                   , final_activation='sigmoid'
                   , use_bn=False)
    print(model.summary())

    print('EMBED 1')
    model = DeepFM({"sparse": sparse_feature_list,
                    "dense": dense_feature_list}
                   , embedding_size=1
                   , use_fm=True
                   , hidden_size=(10,10)
                   , l2_reg_linear=0.0001
                   , l2_reg_embedding=0.00001
                   , l2_reg_deep=0.0001
                   , init_std=0.0001
                   , seed=1024
                   , keep_prob=0.8
                   , activation='relu'
                   , final_activation='sigmoid'
                   , use_bn=False)
    print(model.summary())

```
Here's what I see:

FOR AUTO:
Total params: 123,221
Trainable params: 123,221
Non-trainable params: 0

for EMBED 1:
Total params: 123,222
Trainable params: 123,222
Non-trainable params: 0

I have printed out all the layers and we can see the shape of the fm_input:
FOR AUTO:  
fm_inputshape - (?, 1, 11190) -- deepinputshape - (?, 11190)

for EMBED 1:
fm_inputshape - (?, 11190, 1) -- deepinputshape - (?, 11190)

Also,
>> with EMBED 1, I run out of memory with reasonable batch size,
>> with EMBED AUTO, I do not, and the model compile faster

May you please help explain the difference?

Thanks!
Leo

**Operating environment(运行环境):**
 - python version 3.6
 - tensorflow-gpu version 1.13.0
 - deepctr version  0.2.3

**Comment by shenweichen** [comment]
@leoanghelescu  sorry for this.In fact,the *auto* embedding_size is only  suitable for  *DCN*
