### ISSUE TITLE
Training model in multi gpu environment

### ISSUE THREAD

**Issue by khalidhuseynov** [shenweichen/DeepCTR#55]
**Describe the question(问题描述)**
I've wrapped DeepFM model into `multi_gpu_model` and trying to train on multiple GPUs. However from running time and monitoring gpu utilization, I can see that only one gpu utilized (~50%) at a time while other GPUs are idle (~2%).  Any tips on ways to handle this problem would be appreciated

**Additional context**

**Operating environment(运行环境):**
 - python version 3.6
 - tensorflow version  1.12.0
 - deepctr version 0.3.2

**Comment by leoanghelescu** [comment]
I am also trying to train on multiple GPU. My understanding through this: https://medium.com/@c_61011/why-multi-gpu-training-is-not-faster-f439fe6dd6ec

is that MLP's (fully connected) don't do so well on multiple GPU

My question here is what can we address the scale with these models?

Is a stronger GPU more advantageous than multiple GPU?

Please advise.

Leo




python version 3.6
tensorflow version 1.12.0
deepctr version 0.3.2
