### ISSUE TITLE
DeeoFM模型run_classification_criteo.py文件

### ISSUE THREAD

**Issue by wangtao666666** [shenweichen/DeepCTR#56]
**Describe the question(问题描述)**
A clear and concise description of what the question is.
相同的参数，不同运行结果不一样，但是deepFM随机种子是一样的
![屏幕快照 2019-04-12 下午4 22 45](https://user-images.githubusercontent.com/32592839/56023306-29acee80-5d40-11e9-9bfa-6ae7ab0195bf.png)
![屏幕快照 2019-04-12 下午4 23 11](https://user-images.githubusercontent.com/32592839/56023312-2d407580-5d40-11e9-8a38-59b790210000.png)
![屏幕快照 2019-04-12 下午4 23 37](https://user-images.githubusercontent.com/32592839/56023317-2f0a3900-5d40-11e9-9e89-e894c423d6ee.png)
![屏幕快照 2019-04-12 下午4 24 02](https://user-images.githubusercontent.com/32592839/56023332-316c9300-5d40-11e9-8d36-2473a9b938df.png)

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepctr version [e.g. 0.2.3,]

**Comment by shenweichen** [comment]
一方面是里面确实有一些带有随机性操作的没有被模型的随机种子超参控制住，另一方面是demo数据很少，大概100多条，如果换成较多的数据，其实运行结果是差不都的~

**Comment by Espylapiza** [comment]
遇到了同样的问题，手动调用 np.random.seed 就可以了
