### ISSUE TITLE
如何应用于大数据

### ISSUE THREAD

**Issue by wuminbin** [shenweichen/DeepCTR#58]
**Describe the question(问题描述)**
想问个问题，假设训练数据很大，需要逐行读入处理，需要对输入数据部分做什么改动，最好能有示例代码。

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepctr version [e.g. 0.2.3,]

**Comment by shenweichen** [comment]
您好，针对无法一次性全部读入内存的数据，可以使用`fit-generator`方法替代`fit`方法。
具体用法参考请参考
https://deepctr-doc.readthedocs.io/en/latest/Model_Methods.html#fit-generator

**Comment by wuminbin** [comment]
感谢如此迅速的回复，我去学习下
