### ISSUE TITLE
请问这个包支持多值embeding吗

### ISSUE THREAD

**Issue by mathlf2015** [shenweichen/DeepCTR#6]
比如一个电影有多个标签。这种embeding支持不。。

**Comment by shenweichen** [comment]
Hello,感谢您的关注
这个包是支持多值特征的，但没有在主要models里支持(因为paper本身并没有采用多值特征），主要是在`sequence`模块提供支持，具体如下可以参考文档中这个部分 https://deepctr-doc.readthedocs.io/en/latest/deepctr.sequence.html

下面以简单的pooling操作为例说明，
这里比如说我们输入一个含有多值电影标签的含有两个样本batch数据为
```Python
from deepctr.sequence import SequencePoolingLayer
#首先对变长多值特征进行padding，比如这里我们padding到长度为7
movie_tags = [ [0,1,2,0,0,0,0]，#movie1 具有0，1，2 一共3个标签
 [0,1,2,3,4,0,0]]#movie2 具有0，1，2，3，4 一共5个标签
tags_len = [[3],[5]]#这里记得输入变长特征的有效长度
model_input = [movie_tags,tags_len]
#之后我们可以根据输入拿到对应的embeddding矩阵tag_embedding
#按照API的要求输入embedding矩阵和长度
tags_pooling = SequencePoolingLayer(seq_len_max=7, mode='mean',)(tag_embedding,tags_len_input)
#这样就得到了对变长多值特征的一个定长表示，后续可以进行其他操作

```
![image](https://user-images.githubusercontent.com/18311786/49133255-4b21b680-f31a-11e8-9d29-244120a58ed2.png)

**Comment by mathlf2015** [comment]
谢谢啦。我可以理解为包里面的模型不支持这种多值embeding的特征吗？因为多值不定长的特征在实际做ctr时中还是很常见的。如果我想把这类特征加入到模型有其他办法不？。顺便问下。这个deepctr的模型存储和加载是和keras中的模型储存和加载操作一样的不。

**Comment by shenweichen** [comment]
目前models中只有[DIN](https://deepctr-doc.readthedocs.io/en/latest/deepctr.models.din.html)是原生支持多值embedding输入的。目前除了用DIN的话就只能去修改一下models里的代码，如果你熟悉tensorflow或者Keras的话应该改起来还是蛮快的。

后续我也会给其他model添加一下多值特征的支持，目前主要还没想好一个简洁通用的方式，另外是否能够提供一个含有多值特征的公开数据集？我可以简单的加个demo。

模型的存储和加载操作是和keras models一样的，但是因为modelsl里用了很多自定义的Layer，在`load_model`的时候如果提示找不到Layer在`custom_objects`指定一下就可以了~（这个后续我也会更新到文档里）
感谢你的关注~
