### ISSUE TITLE
How i change the Initializers

### ISSUE THREAD

**Issue by InkdyeHuang** [shenweichen/DeepCTR#61]
**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
Hi @InkdyeHuang 
in deepctr **v0.3.4**,you can modify the code of  initializers of embeding layer in 
`deepctr.input_embedding` line`53-95` ,the code is like
```python
embeddings_initializer=RandomNormal( mean=0.0, stddev=init_std, seed=seed)
```
and for initializers of DNN, look at code at
`deepctr.layers.core` line`144-157`
the code is like
```python
initializer=glorot_normal(seed=self.seed)
```
