### ISSUE TITLE
Is the pypi package sync with latest source code

### ISSUE THREAD

**Issue by debuggy** [shenweichen/DeepCTR#70]
**Describe the question(问题描述)**
When I use ```pip install deepctr```, I found the arguments of DeepFM() is not consistent with those of source code. Which version should I use?

**Operating environment(运行环境):**
 - python version 3.7
 - deepctr version 0.4,0

**Comment by shenweichen** [comment]
@debuggy  Hi, please use `pip install -U deepctr` to install the latest version.
If you have installed `v0.4.0`,it will be consistent with the code at https://github.com/shenweichen/DeepCTR/tree/v0.4.0
