### ISSUE TITLE
new methods 

### ISSUE THREAD

**Issue by yufengwhy** [shenweichen/DeepCTR#73]
**Describe the solution you'd like**
new methods:
1. [lr+gbdt](https://quinonero.net/Publications/predicting-clicks-facebook.pdf)
2. [Tree-enhanced Embedding](https://www.comp.nus.edu.sg/~xiangnan/papers/www18-tem.pdf)

**Comment by zanshuxun** [comment]
> DeepCTR is a Easy-to-use,Modular and Extendible package of **deep-learning** based CTR models
