### ISSUE TITLE
请问,DeepFM支持libffm格式的数据输入吗?

### ISSUE THREAD

**Issue by fly12357** [shenweichen/DeepCTR#74]
因为每一个稀疏特征会有对应的值 例如:  field:feature_index:feature_value

还有, 看了看 multi-value 数据输入的中间结果,  貌似目前不支持.    

之后会支持稀疏格式的数据 例如: libffm 输入吗?

**Comment by shenweichen** [comment]
libffm形式的数据，对于系数特征而言，大部分特征的feature_value都是1。出于简化deepctr使用的目的目前我们限定了只接受稀疏特征的ID输入，不接受特征值（默认特征值为1）。
后续是否会支持libffm格式的输入还不确定~

**Comment by fly12357** [comment]
非常感谢解答. 很赞的项目~star,star

**Comment by kang1916** [comment]
> 对于稀疏特征而言，libffm形式的数据大部分的feature_value都是1。
> deepctr出于简化使用的目的目前限定了只接受稀疏特征的ID输入，不接受特征值（默认特征值为1）。
> 后续是否会支持libffm格式的输入还不确定~

请问现在考虑支持这个了嘛？感谢～
