### ISSUE TITLE
merge_dense_input  in input_embedding.py 

### ISSUE THREAD

**Issue by Phoenixinfire** [shenweichen/DeepCTR#76]
**Describe the question(问题描述)**
It's difficult for me to understand doing embedding for a dense feature,Why we need do that?thx !

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
hi @Phoenixinfire please refer to 
https://deepctr-doc.readthedocs.io/en/latest/Quick-Start.html#step-3-generate-feature-config-dict
Whether doing embedding for dense feature or concat dense feautre with sparse embedding vectors
depends on data and tasks.

**Comment by Phoenixinfire** [comment]
ok ,thank you very much.
