### ISSUE TITLE
关于DIN模型里的Attention部分的逻辑疑问

### ISSUE THREAD

**Issue by eagerming** [shenweichen/DeepCTR#77]
浅梦您好，我是一个tensorflow新手，不太清楚一个地方：

在[DIN模型的LocalActivationUnit模块里](https://github.com/shenweichen/DeepCTR/blob/master/deepctr/layers/core.py#L94)，新建DNN函数是在call()里，也就是每一个user-item对里都会新建一个DNN是吗？

如果是的话，我觉得有点不太合理，因为我理解起来所有的user-item对应该共享同一个DNN才对。

不知道是我的理解有偏差还是代码逻辑有问题。请您指教，谢谢！

**Comment by eagerming** [comment]
补充疑问： 新建这个DNN是否该放进build()里，而非在call()里?

**Comment by shenweichen** [comment]
是共享的，是我忘记把build里的self.dnn用在这里了
不过目前写在call里实际执行的时候并不会多次新建，对结果是没有影响的~

**Comment by xu-song** [comment]
https://github.com/shenweichen/DeepCTR/blob/9564e05ce9b33d6bf2a15779ef6a42831869c390/deepctr/layers/core.py#L101-L105

请问这里的操作，是paper里写的吗？我在paper里好像没找到

**Comment by zanshuxun** [comment]
@xu-song 这两个地方的实现是与DIN作者的开源代码对齐了，与论文中的表述确实不同。具体为什么这样实现，有什么trick，可能还是得去问一下原作者

## concat
concat里加入q-k、q*k，论文里没有体现，是作者开源代码里的实现
https://github.com/zhougr1993/DeepInterestNetwork/blob/9765f96202f849e59ff260c8b46931a0ddf01d77/din/model.py#L209

## softmax
论文中说不需要限制和为1，但代码里是做了softmax
https://github.com/zhougr1993/DeepInterestNetwork/blob/9765f96202f849e59ff260c8b46931a0ddf01d77/din/model.py#L225

**Comment by xu-song** [comment]
感谢
