### ISSUE TITLE
在运行demo时报错AttributeError: 'float' object has no attribute '_unconditional_loss'

### ISSUE THREAD

**Issue by Aone999** [shenweichen/DeepCTR#8]
在运行demo时，报错AttributeError: 'float' object has no attribute '_unconditional_loss'，请问怎么解决？

**Comment by shenweichen** [comment]
确认一下你的tensorflow版本是1.4/1.5/1.6吗，目前只在1.4-1.6测试通过~

**Comment by Aone999** [comment]
谢谢答复，把tensorflow升级到最新版本就解决了

**Comment by shenweichen** [comment]
@Aone999 请安装一下最新版本的DeepCTR `pip install -U deepctr`，新版本兼容了tensorflow 1.4-1.12.0(除了1.7.*和1.8.*)，修复了一些bug~

**Comment by rosefun** [comment]
是的，`pip install -U tensorflow==1.9`解决问题了。
