### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'

### ISSUE THREAD

**Issue by feay1234** [shenweichen/DeepCTR#84]
**Describe the bug**
I got this error when tried to run, python examples/run_dsin.py

**Operating environment:**
 - python version [3.6]
 - tensorflow version [1.13.1]
 - deepctr version [0.4.1]

Thank you very much

**Comment by showkeyjar** [comment]
this error will happen when use tensorflow 1.13, I use tensorflow==1.12 solve this problem.

**Comment by zaccharieramzi** [comment]
I am using tensorflow 1.14 and this issue is still happening. Any idea why ?
