### ISSUE TITLE
请问如何使用梯度截断功能呢？

### ISSUE THREAD

**Issue by zhuangjiayue** [shenweichen/DeepCTR#85]
**Describe the question(问题描述)**
同样的数据，跑了不同的模型，在DeepFM模型上一切正常。
而使用NFFM模型的时候一直梯度爆炸，显示为Nan，请问如何处理这个问题，可以使用梯度阶段吗，该怎么使用呢？

**Additional context**

**Operating environment(运行环境):**
 - python version  3.6
 - tensorflow version [e.g. 1.3.0,]
 - deepctr version [e.g. 0.4,]

**Comment by shenweichen** [comment]
可以的，下面是一个例子
```python
import deepctr
from tensorflow.python.keras.optimizers import Adam,Adagrad

model = deepctr.models.DeepFM({"sparse": sparse_feature_dict, "dense": dense_feature_list})
optimizer = Adagrad('0.01', clipnorm=1)
# optimizer = Adagrad('0.01', clipvalue=1)
model.compile(optimizer,'binary_crossentropy',metrics=['binary_crossentropy'])

```

**Comment by zhuangjiayue** [comment]
> 可以的，下面是一个例子
> 
> ```python
> import deepctr
> from tensorflow.python.keras.optimizers import Adam,Adagrad
> 
> model = deepctr.models.DeepFM({"sparse": sparse_feature_dict, "dense": dense_feature_list})
> optimizer = Adagrad('0.01', clipnorm=1)
> # optimizer = Adagrad('0.01', clipvalue=1)
> model.compile(optimizer,'binary_crossentropy',metrics=['binary_crossentropy'])
> ```

好的，谢谢。还有个几问题请问下：
1.模型的预测是0/1，怎么让模型的预测变成0~1之间的概率呢？
2.为什么我的模型跑出来的预测都是0，需要做正负样本平衡吗？
3.使用AUC作为评价标准，使用什么损失函数的效果会比较好呢？

**Comment by shenweichen** [comment]
1.对于二分类任务，模型的预测就是属于正类的概率
2. 都是0的原因需要具体分析了，通常样本总数足够的情况是不需要做平衡的
3. 可以查阅相关论文，优化auc

**Comment by zhuangjiayue** [comment]
> 1. 对于二分类任务，模型的预测就是属于正类的概率
> 2. 都是0的原因需要具体分析了，通常样本总数足够的情况是不需要做平衡的
> 3. 可以查阅相关论文，优化auc

看了你的知乎，好厉害啊，研究生期间能写出这么棒的东西。应该是我数据出问题了，请问有什么论文推荐吗？还有两个问题：
1.这个怎么多GPU并行啊
2.我的数据量有点大，内存可能不足，如何分块文件读取训练呢？

**Comment by zhuangjiayue** [comment]
> 1. 对于二分类任务，模型的预测就是属于正类的概率
> 2. 都是0的原因需要具体分析了，通常样本总数足够的情况是不需要做平衡的
> 3. 可以查阅相关论文，优化auc

我还以为这个库是哪个组织写的，真的太强了

**Comment by shenweichen** [comment]
感谢使用！
1. 请参考 https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model
2. 请参考 #58

**Comment by zhuangjiayue** [comment]
> 感谢使用！
> 
> 1. 请参考 https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model
> 2. 请参考 #58
好的，谢谢
