### ISSUE TITLE
What is sess_number in DeepCTR/examples/run_dsin.py?

### ISSUE THREAD

**Issue by feay1234** [shenweichen/DeepCTR#86]
DeepCTR/examples/run_dsin.py

Could you please clarify what sess_number in line 24?

Cheers

**Comment by shenweichen** [comment]
`sess_number` is valid session number of each sample。
`sess_number= np.array([2, 1, 0])`indicates the first sample has two valid sesssions,the second sample has one valid sessions,and the third sample has zero session because this user does't have any history behaviors.
