### ISSUE TITLE
关于model的自定义metrics

### ISSUE THREAD

**Issue by srtianxia** [shenweichen/DeepCTR#87]
我可以使用自定义的metrics在model.compile吗 我想在每一轮结束的时候用auc作为指标
```python
def auc(y_true, y_pred):
    auc = K.tf.metrics.auc(y_true, y_pred)[1]
    K.get_session().run(K.tf.local_variables_initializer())
    return auc

model.compile("adam", "binary_crossentropy",
              metrics=[auc])
```
但是用了这个就会报错，这段代码在文本二分类的里面是奏效的，报错信息如下
`tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable linearemb_title_label/embeddings from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/linearemb_title_label/embeddings/N10tensorflow3VarE does not exist.
	 [[{{node loss/embeddings/Regularizer_1/Square/ReadVariableOp}}]]`

**Comment by cl5220418** [comment]
请问您怎么解决的？

**Comment by srtianxia** [comment]
> 请问您怎么解决的？

AUC的计算换成使用`tf.py_func`调用`sklearn`的接口  至于为什么上诉的代码不work 我觉得可能是因为`deepctr`中的所有model都是`tf.keras.model`和原生的model工作机制有些差别。
```python
def auc(y_true, y_pred):
    return tf.py_func(roc_auc_score, (y_true, y_pred), tf.double)
```
