### ISSUE TITLE
怎么把 estimator 和tfrecord 和这个框子联动起来呢

### ISSUE THREAD

**Issue by BigAN** [shenweichen/DeepCTR#88]
**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
这个目前已经做好了，不过是在公司内部做的，后面有可能会公开。

**Comment by wannibar** [comment]
> 这个目前已经做好了，不过是在公司内部做的，后面有可能会公开。

小声温一下快要公开了么～～

**Comment by shenweichen** [comment]
最新版本已经支持tf estimator接口和读取tfrecord格式数据进行训练了
