### ISSUE TITLE
请问这个包支持流数据实时训练吗？

### ISSUE THREAD

**Issue by shijcnju** [shenweichen/DeepCTR#9]
如题。。

**Comment by shenweichen** [comment]
您好，目前从理论上是不支持的哈，因为现在包中的模型底层还是调用tensorflow，tf里的常用的优化算法也是为离线批量学习设计。
不知道您是生产环境使用还是个人学习使用呢？

**Comment by shijcnju** [comment]
我就是学习一下哈
