### ISSUE TITLE
How do you solve the cold-start problem in DSIN?

### ISSUE THREAD

**Issue by vikasmalhotra08** [shenweichen/DeepCTR#90]
**Describe the question(问题描述)**

How do you solve the cold-start problem in DSIN? The cold start problem is the one where you have a user who is visiting a ad for the first time and you are trying to predict CTR based on DSIN.  As you don't have previous session information about the new user, how would DSIN behave for those users?

**Additional context**
I have seen talks where denoising auto-encoders are used to solve the cold start problem but I wanted to get a sense of how this can solved in case of a DIN or DSIN network shared in this repository. 

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
just input padding values for simplicity
