### ISSUE TITLE
关于对dense_input进行embedding能详细解释下

### ISSUE THREAD

**Issue by searchlink** [shenweichen/DeepCTR#91]
**Describe the question(问题描述)**
@shenweichen 非常感谢提供了CTR方面的模型实现！对于sparse变量和sequence变量，都能完全理解embedding的做法，但是对于dense变量，做embedding，不能完全理解merge_dense_input函数的意义，函数返回的embed_list，只是为了确保和sparse和sequence变量保持输出维度都是embedding_size吗？```Dense(embedding_size, use_bias=False, kernel_regularizer=l2(l2_reg), ),dense_input)```,  这里意义是什么？一个float类型的值转变成embedding_size的向量。不能完全理解

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
@shenweichen 对于dense feature，做embedding和concat其实只是处理方式的不同，这里目前是参考的ffm的论文的处理方式~后面我会考虑将其做concat处理

**Comment by searchlink** [comment]
@shenweichen  thx, 希望后续能看到concat处理方式
