### ISSUE TITLE
deep&wide model.fit()

### ISSUE THREAD

**Issue by gongjianwei123** [shenweichen/DeepCTR#92]
**Describe the question(问题描述)**
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 98 array(s), but instead got the following list of 49 arrays: [array([[7],
       [6],
       [6],
       ...,
       [1],
       [3],
       [6]]), array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]]), array([[1],
       [4],
   ...
调用接口形式：history = model.fit(train_model_input, train[target].values,
                        batch_size=256, epochs=10, verbose=2, validation_split=0.2, )

**Comment by gongjianwei123** [comment]
在deep&cross中，model.fit()给输入数据的形式是不是有所不同呢

**Comment by shenweichen** [comment]
请更新最新版本并阅读样例文件
