### ISSUE TITLE
AttributeError: 'SparseFeat' object has no attribute 'hash_flag'

### ISSUE THREAD

**Issue by ulrych8** [shenweichen/DeepCTR#96]
Hello,
First thank you for very useful lib !

I'm trying to predict CTR with Avazu dataset. I'm raising this issue because I have an unexpected error when I want to train my Convolutional CLick Prediction Model.

Here is my code (which is more or less the example code you gave for criteo) :  
---------------------------------------------------------------------------------------------
```python 
sparse_features_list = [SparseFeat(feat, 1000, use_hash=True, dtype='string') 
                              for feat in sparse_features]
dense_features_list = [DenseFeat(feat, 1, ) for feat in dense_features]

model = CCPM({'sparse':sparse_features_list,'dense':dense_features_list},task='binary')
    
model.compile("adam", "binary_crossentropy", metrics=['binary_crossentropy'], )

history = model.fit(train_model_input, train[click].values,
            batch_size=256, epochs=4, verbose=2, validation_split=0.2, )
```
---------------------------------------------------------------------------------------------

This raise the error : 
>>  AttributeError: 'SparseFeat' object has no attribute 'hash_flag'

And the output of  ``` print(sparse_features_list) ``` is : 
>> [SparseFeat(name='site_id', dimension=1000, use_hash=True, dtype='string', embedding_name='site_id', embedding=True),
 SparseFeat(name='site_domain', dimension=1000, use_hash=True, dtype='string', embedding_name='site_domain', embedding=True),
 SparseFeat(name='site_category', dimension=1000, use_hash=True, dtype='string', embedding_name='site_category', embedding=True),
 SparseFeat(name='app_id', dimension=1000, use_hash=True, dtype='string', embedding_name='app_id', embedding=True),
 SparseFeat(name='app_domain', dimension=1000, use_hash=True, dtype='string', embedding_name='app_domain', embedding=True),
 SparseFeat(name='app_category', dimension=1000, use_hash=True, dtype='string', embedding_name='app_category', embedding=True),
 SparseFeat(name='device_id', dimension=1000, use_hash=True, dtype='string', embedding_name='device_id', embedding=True),
 SparseFeat(name='device_ip', dimension=1000, use_hash=True, dtype='string', embedding_name='device_ip', embedding=True),
 SparseFeat(name='device_model', dimension=1000, use_hash=True, dtype='string', embedding_name='device_model', embedding=True)]

However when I tried to replace DenseFeat and SparseFeat by SingleFeat : 
```python 
sparse_feature_list = [SingleFeat(feat, 1000, hash_flag=True, dtype='string') 
                                  for feat in sparse_features]
dense_feature_list = [SingleFeat(feat, 0, ) for feat in dense_features]
```
I have no problem.

*deepctr version [e.g. 0.4.1,]*

**If you could help me to understand what I do wrong, and what should be done in my situation, I would really appreciate.**

**Comment by ulrych8** [comment]
Here I found a way to solve the problem; you have to change the classe SparseFeat
```python
class SparseFeat(namedtuple('SparseFeat', ['name', 'dimension', 'hash_flag', 'dtype','embedding_name','embedding'])):
    __slots__ = ()

    def __new__(cls, name, dimension, hash_flag=False, dtype="int32", embedding_name=None,embedding=True):
        if embedding and embedding_name is None:
            embedding_name = name
        return super(SparseFeat, cls).__new__(cls, name, dimension, hash_flag, dtype, embedding_name,embedding)
    ```
I don't close the issue so you can see the problem

**Comment by shenweichen** [comment]
please update your deepctr version to v0.5.0
