### ISSUE TITLE
Litlle mistake

### ISSUE THREAD

**Issue by ulrych8** [shenweichen/DeepCTR#97]
![image](https://user-images.githubusercontent.com/32176478/60441197-c633ae00-9c16-11e9-912b-09cca6cb4e44.png)

There is no **linear_feature_columns** in the parameters of the function. This is not really important but I just wanted to let you know

https://deepctr-doc.readthedocs.io/en/latest/deepctr.models.pnn.html

And the doc for Field-aware Neural Factorization Machine at https://deepctr-doc.readthedocs.io/en/latest/deepctr.models.nffm.html is vacuum

**Comment by shenweichen** [comment]
Thanks, the docs have been fixed.
