### ISSUE TITLE
SparseFeat import failed

### ISSUE THREAD

**Issue by jt120** [shenweichen/DeepCTR#98]
**Describe the bug(问题描述)**
new version should use 
```
from deepctr.inputs import  SparseFeat, DenseFeat,get_fixlen_feature_names
```
not
```
from deepctr.utils import SparseFeat,DenseFeat
```
**To Reproduce(复现步骤)**
- need upgrade document
https://deepctr-doc.readthedocs.io/en/latest/Examples.html#classification-criteo

**Comment by shenweichen** [comment]
thanks, i have updated the docs.
